### ISSUE TITLE
Allow devServer to serve cleanURL

### ISSUE THREAD

**Issue by octref** [vuejs/vuepress#603] opened 2018-06-19 02:59 UTC
#### What problem does this feature solve?

When requesting `/about`, serve `/about.html` without redirect.

#### What does the proposed API look like?

In config.js, have `cleanURL: true` by default.
When enabled, it will serve Clean URL like [surge.sh](https://surge.sh/help/using-clean-urls-automatically) or zeit's [serve](https://github.com/zeit/serve-handler#cleanurls-booleanarray).

#### How should this be implemented in your opinion?

Some rule rewrites in the webpack-serve or koa part.

#### Are you willing to work on this yourself?

Don't have enough time, sorry.

**Comment by Gangwolf** [comment] 2018-06-19 04:54
😄 I was just about to open an issue on this, would be a great API! Btw, just as a quick add on, I noticed that having a path serve as a page and as a directory works only if a trailing slash is used:
.
├─ articles                        
│  ├─ README.md            
│  └─ some-article.md

'/articles' => Returns only \<Root\> component, empty page but not a 404 
'/articles/' => Returns all appropriate components for README, renders correctly
'/articles/some-article.html' => Returns all appropriate components for some-article, renders correctly

Perhaps this can be addressed with this issue as well...

**Comment by ulivz** [comment] 2018-06-19 16:50
@octref In favor of that, and we need to distinguish these two different scenarios:

- Source file: `/about/index.md`, serve `/about/index.html`
- Source file: `/about.md`, serve `/about.html`

@Gangwolf `/articles` isn't a semantic URL for `/articles/REAMD.md`, so please make sure that it URL ends with a slash.

**Comment by octref** [comment] 2018-06-19 17:03
@ulivz I think surge's rule for handling this is pretty straightforward: https://surge.sh/help/using-clean-urls-automatically

#### For request `/foo`

- Serve `/foo.html`
- If `/foo.html` isn't available
  - Redirect to `/foo/`
  - Serve `/foo/index.html`, which can be either `/foo/index.md` or `/foo/readme.md`

#### For request `/foo/`

- If `/foo.html` is available
  - Redirect to `/foo`
  - Serve `/foo.html`
- If `/foo.html` is not available but `/foo/index.html` is, serve that, which can be either `/foo/index.md` or `/foo/readme.md`

**Comment by octref** [comment] 2018-06-19 17:05
@Gangwolf 
And for the request `/articles`, if `/articles.md` is available it should serve that. Otherwise it should **redirect** to `/articles/` and serve the compiled html from `/articles/[index|readme].md`

**Comment by ulivz** [comment] 2018-06-19 17:07
@octref Awesome!

Maybe I need spend time researching whether all other mundane uses can also support such features, e.g. Github Pages / netlify.

**Comment by octref** [comment] 2018-06-19 17:10
Netlify also supports it https://www.netlify.com/docs/redirects/#trailing-slash

I do think GitHub support it too.

**Comment by ulivz** [comment] 2018-06-19 17:14
Cool, let's plan for it.

**Comment by Gangwolf** [comment] 2018-06-19 23:41
@ulivz @octref, thanks for clarifying 👍

**Comment by AWulkan** [comment] 2018-06-25 11:33
Isn't there a drawback to this though? The redirects on the webhosts will cause a full page reload. This is not really wanted behavior with Vue.

Wouldn't it be better to generate a file structure when building? So that the site enables clean URLs by default, to take advantage of the client side routing.

**Comment by Wangszzju** [comment] 2018-08-12 02:44
@octref Hey, My opinion of the issue is same to you！
Would you please check my [Pull Request](https://github.com/vuejs/vuepress/pull/722) and give me some suggestion？That's my solution but I'm not sure whethor the solution is elegant or not.

**Comment by Wangszzju** [comment] 2018-08-12 02:50
@meteorlxy 
since the issue #720 has been closed, maybe we can have discussion here?
 I also think url without trailing slash looks better. However, when you have these files:
* `/config.md`
* `/config/README.md`
If you have both of them, of course the url `/config` and the `/config/` should be different.However, if you have only one of them, maybe we really need redirect? 
 I sincerely wonder what your opinion about the situation is.

**Comment by ycmjason** [comment] 2018-08-12 05:02
I don't understand why it matters how the URL looks in devServer. You can set this up in prod easily if you wish.

**Comment by ycmjason** [comment] 2018-08-12 05:04
IMHO, introducing this might incur unnecessary complexity in the URL resolving logic. I prefer to keep this simple and straightforward.

**Comment by octref** [comment] 2018-08-12 06:35
@Wangszzju 

https://github.com/vuejs/vuepress/issues/603#issuecomment-398472571

![image](https://user-images.githubusercontent.com/4033249/43999306-b06d7850-9dbe-11e8-9fe2-1b86979c8667.png)

@ycmjason 

It's not just how the URL **looks**. It's how the devServer **behaves**.

For me, I prefer to organize subpages like this:
```
file -> dist -> url
/posts/foo.md -> /posts/foo.html -> /posts/foo
/posts/bar.md -> /posts/bar.html -> /posts/bar
/posts/baz.md -> /posts/baz.html -> /posts/baz
```
But now when I request `/posts/foo` on devServer, it redirects to `/posts/foo/` and try to serve `/posts/foo/index.html`. That causes **404** and is inconsistent with my prod server.

If I organize my file like this:
```
/posts/foo/index.md
/posts/bar/index.md
/posts/baz/index.md
```
It at least works on devServer, but now I end up with URL with ugly trailing slashes.

**Comment by mathiasbynens** [comment] 2018-08-14 08:32
FWIW, Firebase supports this too through the `cleanUrls` setting: https://firebase.google.com/docs/hosting/full-config#cleanurls

It would be great to have the dev server support “clean URL” behavior as available on all these hosting platforms.

**Comment by ulivz** [comment] 2019-02-08 14:29
Before actually starting to support this feature, I created a [PR: feat($core): redirects for clean urls](https://github.com/vuejs/vuepress/issues/608) as a transition solution.

**Comment by Shigma** [comment] 2019-03-08 13:32
Fixed.

**Closed by Shigma** 2019-03-08 13:32 UTC
Labels: feature request
