### ISSUE TITLE
Latest alpha 1.0.0-alpha.16 throws some exceptions when starting it

### ISSUE THREAD

**Issue by rajaraodv** [vuejs/vuepress#959] opened 2018-10-26 20:40 UTC
#### Version
`1.0.0-alpha.16`

#### Steps to reproduce

```
> vuepress dev docs


 WAIT  Extracting site metadata...

 TIP  Temp directory: /usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/.temp
TypeError: Cannot read property 'endsWith' of null
    at loadTheme (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/prepare/loadTheme.js:53:20)
    at AppContext.resolveTheme (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/prepare/AppContext.js:270:32)
    at AppContext.process (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/prepare/AppContext.js:77:16)
    at prepare (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/prepare/index.js:15:20)
    at dev (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/dev.js:23:21)
    at args (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/cli/index.js:120:14)
    at Command.program.command.description.option.option.option.option.option.option.action (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/cli/index.js:50:23)
    at Command.listener (/usr/local/lib/node_modules/vuepress/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/vuepress/node_modules/commander/index.js:654:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testautomationu@0.0.1 docs:dev: `vuepress dev docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testautomationu@0.0.1 docs:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raja.rao/.npm/_logs/2018-10-26T20_37_28_630Z-debug.log
```

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by x8x** [comment] 2018-10-29 09:10
Duplicate of https://github.com/vuejs/vuepress/issues/949 ?

**Comment by ulivz** [comment] 2018-11-07 18:52
It should be fixed at the latest alpha version.

**Closed by ulivz** 2018-11-07 18:52 UTC
