### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by collymore** [vuejs/vuepress#443] opened 2018-05-13 22:08 UTC
I'm trying to use a Vue component from the node_modules folder. It works correctly when running as ```vuepress dev``` but not when ```vuepress build``` 

Installed with Yarn by running
``` yarn add vue-carousel-3d ```

and imported within 
```.vuepress/enhanceApp.js```

```
import { Carousel3d } from 'vue-carousel-3d';

export default ({
    Vue, // the version of Vue being used in the VuePress app
    options, // the options for the root Vue instance
    router, // the router instance for the app
    siteData // site metadata
  }) => {
    Vue.component('carousel3d', Carousel3d);
}
```
Runing ```Vuepress build``` returns

```
Rendering static HTML...
Rendering page: /Error rendering /:
Error: Cannot find module 'vue-carousel-3d'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at r (/Users/lukecollymore/.config/yarn/global/node_modules/vue-server-renderer/build.js:8335:16)
    at Object.module.exports.__WEBPACK_AMD_DEFINE_FACTORY__ (webpack:/external "vue-carousel-3d":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:3315:33)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:3634:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:103:18
    at Object.<anonymous> (server-bundle.js:106:10)
    at evaluateModule (/Users/lukecollymore/.config/yarn/global/node_modules/vue-server-renderer/build.js:8338:21)
    at /Users/lukecollymore/.config/yarn/global/node_modules/vue-server-renderer/build.js:8396:18
    at new Promise (<anonymous>)
```

What else do I need to do for this to build?

- OSX  10.13.2
- Node.js v8.9.1
- Yarn 1.6.0
- VuePress 0.8.4

**Comment by ulivz** [comment] 2018-05-14 01:31
Do you install VuePress globally? BTW, is there any reproduced repo?

**Comment by collymore** [comment] 2018-05-14 06:26
Yes Vuepress is installed Globally.  I will setup a repo today. Thanks

**Comment by meteorlxy** [comment] 2018-05-14 06:32
@collymore Suggest to install vuepress locally at current version. Global cli still have some issues

**Comment by meteorlxy** [comment] 2018-05-14 06:34
btw, as a temporary solution, #353 may help

**Comment by ulivz** [comment] 2018-05-14 13:54
@collymore  Sorry, I just download your repo and cannot reproduce it: 

![image](https://user-images.githubusercontent.com/23133919/40001629-3270ecea-57c1-11e8-8f24-3c8741d650f3.png)

**Comment by collymore** [comment] 2018-05-14 14:47
Thanks for taking a look, I've just setup another Mac and an Ubuntu computer and both error at that same point. 

<img width="1094" alt="screen shot 2018-05-14 at 15 04 07" src="https://user-images.githubusercontent.com/55946/40002285-289d6a60-5788-11e8-8573-7e77d8c8b138.png">

Mac OSX
yarn -v   1.6.0
node -v  v8.3.0

Ubuntu 14.04.5 LTS
node -v v8.11.1
Yarn - 1.6.0

Can you let me know what versions you were using?

**Comment by ulivz** [comment] 2018-05-15 15:19
Oh, it's truly an issue, I reproduced it. 

For now, you can use relative path to get a quick fix:

Change:

``` js
import vueConfirmationButton from 'vue-confirmation-button/dist/vue-confirmation-button.vue';
```

To:

``` js
import vueConfirmationButton from '../../node_modules/vue-confirmation-button/dist/vue-confirmation-button.vue';
```

But it works at `dev`, and only doesn't work at `build`. i need do more investigation.

**Comment by ulivz** [comment] 2018-05-15 15:30
@yyx990803 I tried to find out the root of the weird issue, checked the vue-loader's code & doc and our internal config, but still cannot get specific answer.

The fastest reproduction is:

1. Add following code at `lib/app/app.js`:

``` js
import CarbonAds from 'vuepress-theme-vue/CarbonAds.vue'
Vue.component('CarbonAds', CarbonAds)
```

2. `yarn dev` work properly, but run `yarn build` you'll get the error:

``` 
Rendering page: /Error rendering /:
/Users/haolchen/Documents/__self__/__forked__/vuepress/node_modules/vuepress-theme-vue/CarbonAds.vue:1
(function (exports, require, module, __filename, __dirname) { <script>
                                                              ^

SyntaxError: Unexpected token <
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at r (/Users/haolchen/Documents/__self__/__forked__/vuepress/node_modules/vue-server-renderer/build.js:8335:16)
    at Object.vuepress-theme-vue/CarbonAds.vue (webpack:/external "vuepress-theme-vue/CarbonAds.vue":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object../lib/app/app.js (lib/app/app.js:5:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object../lib/app/serverEntry.js (lib/app/serverEntry.js:1:0)
```

3. then, modify the code in step1 to:

``` js
import CarbonAds from '../../node_modules/vuepress-theme-vue/CarbonAds.vue'
Vue.component('CarbonAds', CarbonAds)
```
all will work after this change.

That is to say, when we import a SFC from dependency, we must import it in `absolute path` or `relative path` instead of `[moduleName]/rest-relative-path`. Otherwise, it will cause the build to be wrong.

Do you have any advice? thanks!

**Comment by ulivz** [comment] 2018-05-15 15:39
Closing this since the 1st issue cannot be reproduced, for the 2nd issue, let's go #451.

**Closed by ulivz** 2018-05-15 15:39 UTC
