### ISSUE TITLE
Cann't use image when globally installed

### ISSUE THREAD

**Issue by maimake** [vuejs/vuepress#752] opened 2018-08-20 03:20 UTC
#### Version

0.14.2

#### Steps to reproduce

1. install vuepress
```bash 
yarn global add vuepress
```

2. copy an image named ooo.png

3. use image in README.md as following:
```markdown
# Hello VuePress

![ooo](./ooo.png)
```

4. dev
```bash
vuepress dev
```

#### What is expected?

Wanna see an image in browser

#### What is actually happening?

got an error😟
```
ERROR in ./ooo.png
Module build failed (from /Users/mai/.config/yarn/global/node_modules/url-loader/dist/cjs.js):
TypeError: Cannot read property 'context' of undefined
    at Object.module.exports (/Users/mai/.config/yarn/global/node_modules/file-loader/index.js:12:42)
    at Object.loader (/Users/mai/.config/yarn/global/node_modules/url-loader/dist/index.js:61:19)
 @ ./README.md?vue&type=template&id=0290eea1& (/Users/mai/.config/yarn/global/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"../../../../.config/yarn/global/node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"14699666-vue-loader-template"}!/Users/mai/.config/yarn/global/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!/Users/mai/.config/yarn/global/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js??ref--1-0!/Users/mai/.config/yarn/global/node_modules/vue-loader/lib??ref--1-1!/Users/mai/.config/yarn/global/node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./README.md?vue&type=template&id=0290eea1&) 25:41-61
 @ ./README.md?vue&type=template&id=0290eea1&
 @ ./README.md
 @ /Users/mai/.config/yarn/global/node_modules/vuepress/lib/app/.temp/routes.js
 @ /Users/mai/.config/yarn/global/node_modules/vuepress/lib/app/app.js
 @ /Users/mai/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
 @ multi /Users/mai/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
```

#### Other relevant information

- Your OS:  Macos 10.13.4 
- Node.js version:  v10.8.0
- Browser version: Chrome 68.0.3440.106
- Is this a global or local install? GLOBAL
- Which package manager did you use for the install? yarn

**Comment by ldexterldesign** [comment] 2018-08-20 07:26
Hi,

If your image file isn't inside `docs/ooo.png` then try putting it there

Regards

**Comment by maimake** [comment] 2018-08-20 08:33
So sad! Still not working.
I move files into `docs/` and run `vuepress dev docs`, and got the same error message

Here are my files:
```
.
└── docs
    ├── README.md
    └── ooo.png


```

**Comment by ulivz** [comment] 2018-08-20 10:01
1. Please submit an issue in the normal tone 🙂 
2. This is a global-only issue.

**Comment by maimake** [comment] 2018-08-20 10:07
@ulivz You saved my life , thx ! 
I can use it now with local dependency. Have fun

**Comment by ulivz** [comment] 2018-08-21 12:10
Closing it since I cannot reproduce it, and feel free to continue discussion if you can provide a proper reproduction step.

**Closed** 2018-08-21 12:10 UTC
Labels: Needs More Info 🤷‍♂️
