### ISSUE TITLE
Why css 、ttf 、woff path is correct ，but vuepress tell me it's incorrect？

### ISSUE THREAD

**Issue by MissNanLan** [vuejs/vuepress#1733] opened 2019-08-01 08:44 UTC
- [ ] I confirm that this is an issue rather than a question.

#### What is expected?
No error

#### What is actually happening?
![image](https://user-images.githubusercontent.com/22790863/62278675-21a5c580-b47b-11e9-8a32-d5a7ddc3431d.png)

vuepress console error message

![image](https://user-images.githubusercontent.com/22790863/62278709-33876880-b47b-11e9-94f7-40bad37addcb.png)

Why??

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by kefranabg** [comment] 2019-08-08 15:12
Hi @MissNanLan,

From what I'm reading in the logs, your error is actually occurring in your component named `nanlan-card.vue`, not in `icon.sccss` file.

Can you confirm ?

**Comment by MissNanLan** [comment] 2019-08-09 02:49
but I change nanlan.css to nanlan.scss , no error. I suspect can‘t parse css file,and I aslo have a question, it cannot parse relative path。



but I change nanlan.css to nanlan.scss , no error. I suspect can‘t parse css file,and I aslo have a question, it cannot parse relative path。

**Comment by kefranabg** [comment] 2019-08-09 08:18
Could you provide a reproduction link?

**Comment by billyyyyy3320** [comment] 2020-08-29 15:19
Close it since it's been a year without reproduction.

BTW, you might like to read [the warning container under this section](https://vuepress.vuejs.org/config/#index-styl)

**Closed by billyyyyy3320** 2020-08-29 15:19 UTC
Labels: needs reproduction
