### ISSUE TITLE
must emit AsyncMarkdownContentMounted

### ISSUE THREAD

**Issue by bailnl** [vuejs/vuepress#1022] opened 2018-11-18 12:22 UTC
If you customize `<script/>`, you must write your own [slotKey](https://github.com/vuejs/vuepress/issues/975) and $emit `AsyncMarkdownContentMounted` event

https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown-loader/index.js#L110

If it doesn't trigger, it will report an error when switching pages.
destroy of undefined,   this.$smoothScroll is undefined

![image](https://user-images.githubusercontent.com/2436993/48672282-06a25800-eb6f-11e8-8349-96fd3a3ba349.png)

#### Version
"vuepress": "^1.0.0-alpha.23",

**Comment by ulivz** [comment] 2018-11-18 16:41
Thanks for your report, but it's duplicate of #975, let's move here to continue.

FYI. for now do not write `<script>` at markdown file. (You can put them under a Vue component), we'll fix it before we reach `beta` stage.

**Closed by ulivz** 2018-11-18 16:41 UTC

**Comment by ulivz** [comment] 2018-12-12 17:55
Fixed at https://github.com/vuejs/vuepress/commit/ece2e1e09ad5e48c48861330bb79f98880f90028 and out at `vuepress/1.0.0-alpha.28`
