### ISSUE TITLE
Error when referring to pictures in parent path in Markdown file

### ISSUE THREAD

**Issue by yindaheng98** [vuejs/vuepress#2487] opened 2020-07-13 11:03 UTC
- [√] I confirm that this is an issue rather than a question.

## Bug report
```
Error: Failed to compile with errors.
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/node/build/index.js:180:16
    at finalCallback (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/tapable/lib/Hook.js:154:20)
    at /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:678:31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepress-starter@1.0.0 docs:build: `vuepress build docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuepress-starter@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-13T10_33_44_689Z-debug.log
```

and the "/root/.npm/_logs/2020-07-13T10_33_44_689Z-debug.log" is:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/yin/.nvm/versions/node/v12.18.1/bin/node',
1 verbose cli   '/home/yin/.nvm/versions/node/v12.18.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'docs:build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'predocs:build', 'docs:build', 'postdocs:build' ]
5 info lifecycle vuepress-starter@1.0.0~predocs:build: vuepress-starter@1.0.0
6 info lifecycle vuepress-starter@1.0.0~docs:build: vuepress-starter@1.0.0
7 verbose lifecycle vuepress-starter@1.0.0~docs:build: unsafe-perm in lifecycle true
8 verbose lifecycle vuepress-starter@1.0.0~docs:build: PATH: /home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/MyPrograms/vuepress-starter/node_modules/.bin:/home/yin/.nvm/versions/node/v12.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle vuepress-starter@1.0.0~docs:build: CWD: /home/MyPrograms/vuepress-starter
10 silly lifecycle vuepress-starter@1.0.0~docs:build: Args: [ '-c', 'vuepress build docs' ]
11 silly lifecycle vuepress-starter@1.0.0~docs:build: Returned: code: 1  signal: null
12 info lifecycle vuepress-starter@1.0.0~docs:build: Failed to exec docs:build script
13 verbose stack Error: vuepress-starter@1.0.0 docs:build: `vuepress build docs`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/yin/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid vuepress-starter@1.0.0
15 verbose cwd /home/MyPrograms/vuepress-starter
16 verbose Linux 4.15.0-109-generic
17 verbose argv "/home/yin/.nvm/versions/node/v12.18.1/bin/node" "/home/yin/.nvm/versions/node/v12.18.1/bin/npm" "run" "docs:build"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error vuepress-starter@1.0.0 docs:build: `vuepress build docs`
22 error Exit status 1
23 error Failed at the vuepress-starter@1.0.0 docs:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
#### Steps to reproduce

For example, I have a dir:
* parent_dir
  * child_dir
    * article.md
  * img
    * some_pic.png

And I write `![This is a img](../img/some_pic.png)` in `article.md`, then `vuepress build parent_dir`, the error appear.

If I place the img folder into child_dir:

* parent_dir
  * child_dir
    * article.md
    * img
      * some_pic.png

and write `![This is a img](./img/some_pic.png)` rather than `![This is a img](../img/some_pic.png)` in `article.md`, `vuepress build parent_dir` run normally.

#### What is expected?

I think the image in parent dir (obviously not outside the project dir) should be able to refer to in Markdown.

#### What is actually happening?

Referring to the image in parent dir (not outside the project dir) cause the error showed above.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.18.1 - /home/yin/.nvm/versions/node/v12.18.1/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /home/yin/.nvm/versions/node/v12.18.1/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: 1.5.2
```

**Comment by kefranabg** [comment] 2020-07-14 09:41
Hi @yindaheng98, I'm not able to reproduce your issue. Please provide a reproduction link so we can investigate.

**Comment by kefranabg** [comment] 2020-07-18 09:14
I'm closing this issue for now, feel free to reopen it with a reproduction link.

**Closed by kefranabg** 2020-07-18 09:14 UTC
Labels: needs reproduction
