### ISSUE TITLE
Build error when import SFC from dependency.

### ISSUE THREAD

**Issue by nikhilkul** [vuejs/vuepress#666] opened 2018-07-24 00:07 UTC
#### Version
0.12.0

#### Steps to reproduce

1.  Clone [reproduction repo](https://github.com/nikhilkul/vuepress-test)
2. `yarn install`
3. `yarn global add vuepress`
4. `yarn docs:build` -> Fails with 

```bash
╰─$ yarn docs:build                                                      130 ↵
yarn run v1.7.0
$ vuepress build docs

 WAIT  Extracting site metadata...
<product2></product2>
[4:51:09 PM] Compiling Client
[4:51:09 PM] Compiling Server
(node:17386) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
<product2></product2>
[4:51:14 PM] Compiled Server in 5s
[4:51:16 PM] Compiled Client in 7s
 WAIT  Rendering static HTML...
Rendering page: / FAIL  Error rendering /:
Error: render function or template not defined in component: product2
    at normalizeRender (/Users/z00335s/gitdir/vuepress-test/node_modules/vue-server-renderer/build.js:7396:13)
    at renderComponentInner (/Users/z00335s/gitdir/vuepress-test/node_modules/vue-server-renderer/build.js:7520:3)
    at renderComponent (/Users/z00335s/gitdir/vuepress-test/node_modules/vue-server-renderer/build.js:7491:5)
    at resolve (/Users/z00335s/gitdir/vuepress-test/node_modules/vue-server-renderer/build.js:7552:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### What is expected?

`yarn docs:build` should not fail if `yarn docs:dev` is not throwing any error.

#### What is actually happening?

When I remove following imports, in `docs/.vuepress/components/product2.vue` the build works.

```js
import DatePicker from "vue2-datepicker";
Vue.component('DatePicker', DatePicker)
```

#### Other relevant information

- Your OS: **MacOs Sierra 10.12.6**
- Node.js version: **10.7**
- Browser version: **No need**
- Is this a global or local install? : **Global**
- Which package manager did you use for the install? : **Yarn**

**Comment by ulivz** [comment] 2018-07-25 10:15
Duplicate of #451, please step over there to see the workaround.

**Closed by ulivz** 2018-07-25 10:15 UTC
Labels: duplicate, has workaround

**Comment by nikhilkul** [comment] 2018-07-27 05:04
#451 says add code to `lib/app/app.js`. 
Does that mean I have to create a new file `app.js` at this path `docs/.vuepress/app.js` ? 

Changing `import DatePicker from 'vue2-datepicker';` to `import DatePicker from '../../../node_modules/vue2-datepicker;` in the reproduction repository mentioned above does not solve the issue.
The library that I am trying to import, does not have a `.vue` file at root path. 

I tried following:

1. `import DatePicker from '../../../node_modules/vue2-datepicker/src/index.vue;`
2. `import DatePicker from '../../../node_modules/vue2-datepicker`

Both didn't work.

**Comment by nikhilkul** [comment] 2018-07-31 01:05
@ulivz Can you please help me for this ⏫
