### ISSUE TITLE
Hot reload doesn't reflect frontmatter nor config.js changes

### ISSUE THREAD

**Issue by SimonEast** [vuejs/vuepress#1283] opened 2019-02-12 07:35 UTC
- [x] I confirm that this is a issue rather than a question.

## Bug report

The hot reload functionality when using `vuepress dev` does not seem to pickup changes to:

* `*.md` frontmatter
* `.vuepress/config.js`

I'm new to VuePress so not sure if this was this previously working in earlier versions, but not working in `1.0.0-alpha.37`.

#### Version

1.0.0-alpha.37

#### Steps to reproduce

1. Install vuepress@next globally - `yarn global add vuepress@next`

2. Start with empty folder and a single `README.md` file, with a few headings

3. Create a `.vuepress/config.js` file and enable a sidebar:

       themeConfig: {
  	     sidebar: ['/']
       }

2. Run `vuepress dev` and view in browser

3. Add frontmatter to `README.md` such as:

       ---
       title: X
       ---

4. Nothing happens. Content changes are reloaded, but none of the frontmatter data.

5. Add another sidebar item to `config.js`

6. Again, the browser is not updated.

Not even a browser refresh helps in either of these issues. I have to quit the dev server and restart it for the frontmatter and new sidebar elements to be reflected in the browser.

#### What is expected?

I would expect the frontmatter data to be rescanned and injected into the page and reflected in sidebars.

#### What is actually happening?

Content changes are hot reloaded, but none of the frontmatter data nor `config.js` changes.

#### Other relevant information

- Your OS: Windows 10
- Node.js version: 10.2.1
- Browser version: Chrome 73.0.3683.27 beta
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

**Comment by SGarno** [comment] 2019-03-28 03:48
This is the same behavior I am experiencing in the latest pull of 1.x.    I have worked extensively with 0.x and it works fine in that version.   

Is this something that is on the near term radar for being fixed?

**Comment by timaschew** [comment] 2019-04-02 07:30
Frontmatter changes do work with version `1.0.0-alpha.44`.

Also changes in the **.vuepress/config.js** are working, the title is refreshed in the sidebar.

To be fair: it only works for existing sidebar entries. So adding or deleting items doesn't work!

**Comment by SimonEast** [comment] 2019-04-18 03:46
I've tried again in 1.0.0-alpha/47 and *none* of these changes are being hot reloaded:

* Adding/editing frontmatter titles
* Changing anything in `.vuepress/config.js`
* Sidebars and sidebar config
* Adding a new `.md` file

My VuePress console window tells me:

    Reload due to change .vuepress\config.js

But then nothing is updated in my browser - not even after a manual refresh.

Is this different to what you're experiencing @timaschew?

**Comment by jshor** [comment] 2019-05-25 15:49
+1

**Comment by sindrepm** [comment] 2019-05-27 11:45
+1

**Comment by favoyang** [comment] 2019-07-27 13:18
Same here. vuepress@1.0.2 installed globally via yarn.

Environment Info:     
```
$ vuepress info                                                      
...                         
  System:                                                            
    OS: Windows 10                                                   
    CPU: (8) x64 Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz           
  Binaries:                                                          
    Node: 10.9.0 - C:\Program Files\nodejs\node.EXE                  
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD          
    npm: 6.10.0 - ~\AppData\Roaming\npm\npm.CMD                      
  Browsers:                                                          
    Edge: 44.18362.1.0                                               
  npmPackages:                                                       
    @vuepress/core: Not Found                                        
    @vuepress/theme-default: Not Found                               
    vuepress: Not Found                                              
  npmGlobalPackages:                                                 
    vuepress: Not Found                                              
```

Create a page named "new-page.md". Console detected the changes, but visit /new-page returns 404.
```
success [21:08:12] Build 9bda3d finished in 11198 ms!
> VuePress dev server listening at http://localhost:8080/
Reload due to add new-page.md
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
```

Update .vuepress/config.js (like title). Console detected the chagnes, but browser does not update. Force refresh won't work either.
```
eload due to change .vuepress\config.js
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
Reload due to change .vuepress\config.js
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
warning Override existing page /.
warning Override existing page /about.html.
...
warning Override existing page /new-page.html.
```

However, update existing page works as expected.

Relaunch vuepress dev server will fix everything.

**Comment by favoyang** [comment] 2019-07-27 14:17
Refs https://github.com/vuejs/vuepress/issues/1536

I tried run with ```vuepress dev docs --temp .temp```, and update config.js now trigger my refresh correctly, so does add new page.

However I meet a new issue that all custom componet failed after reload. Force refresh won't fix it either. But I do find a trick that create or rename a md file will fix it.

```
Browser console: 
[Vue warn]: Unknown custom element: <List> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by quanzaiyu** [comment] 2019-07-31 07:05
It takes effect when I changed some dynamically configurations, but changing fontmatter didn't work.

Some dynamically configurations related files are as follows:

`website\.vuepress\plugins\enhanceAppFiles\generateSidebars.js`

![未命名1564556356](https://user-images.githubusercontent.com/13745132/62190410-e1bfdf00-b3a3-11e9-94f1-6a2da17bbfa1.png)


`website\.vuepress\plugins\enhanceAppFiles\index.js`

![未命名1564554702](https://user-images.githubusercontent.com/13745132/62188825-1df14080-b3a0-11e9-8890-89e465d86012.png)

`website\.vuepress\config.js`

![未命名1564554887](https://user-images.githubusercontent.com/13745132/62188976-70caf800-b3a0-11e9-9ded-8793a1acd500.png)

I specify script in frontmatter:

`website\books\canvas\index.md`

![未命名1564555060](https://user-images.githubusercontent.com/13745132/62189134-d5865280-b3a0-11e9-94b9-18e28b6a36da.png)

---

It takes effect when changing file `website\books\canvas\index.js` 

![未命名1564555238](https://user-images.githubusercontent.com/13745132/62189360-52193100-b3a1-11e9-8404-b80228faa107.png)

modified：

![未命名1564555639](https://user-images.githubusercontent.com/13745132/62189672-32363d00-b3a2-11e9-8b14-0b175717331e.png)

It works and there are two more menus in the sidebar

---

But it does not take effect when changing file `website\books\canvas\index.md` frontmatter

such as：

![未命名1564555439](https://user-images.githubusercontent.com/13745132/62189495-af14e700-b3a1-11e9-941a-8fe9d629a046.png)

It doesn't work!

`/books/canvas_test` got 404

`/books/canvas` still can be accessed

**Comment by liudonghua123** [comment] 2019-09-05 01:39
I have the same problems. Everytime I modified the configuration files in `.vuepress`, The console logs shown detected the changes, but the page in browser did not changes. All I can do is `ctrl+c` , `arrow up` and `enter` to restart it manually.

**Comment by ludanxer** [comment] 2019-10-16 05:50
First, as @favoyang mentioned above,  #1536 is duplicate with this issue. It did, however, bring up a workaround: `--temp .temp`. I comment here because #1536 is filled with Chinese.

I tried to fix this but failed. For what it's worth, I will leave what I found here.

I believe this problem can **only be reproduced on Windows**. I find that everyone who display their OS in the two issues are using Windows, and test it on my roommate's pc (Windows 10). Hot reload is indeed not working when I change `config.js`.

Hot reload is working fine on my Mac, and in the **official repo even on Windows**. At first, I thought it's [chokidar](https://github.com/paulmillr/chokidar)'s versioning problem (Vuepress is using chokidar in `core/node/dev/index.js` to watch changes right?). Because the official repo workspace docs is using `3.0.2` because of `remark-cli`, but if you install Vuepress as a dependency, you will get `2.1.8`.  Besides chokidar does have some [windows labeled issues](https://github.com/paulmillr/chokidar/issues?utf8=%E2%9C%93&q=label%3Awindows+)

But that's not the case, I try to remove some packages in official repo's workspace docs's package.json so it will also use `2.1.8`. The hot reload is still working.

I also tried to use [yarn Selective dependency resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions) to only bump chokidar's version to the `3.2.1` or `3.0.2` in my own project,  it starts to hot reload when I change `config.js` but stop to response to changes in `*.md` files...

BTW, I think we should bump workspace docs chokidar's `3.0.2` version anyway, because [this issue in chokidar](https://github.com/paulmillr/chokidar/issues/871)

Hope this helps. Someone pls test this cause I'm not familiar with this and in a hurry to return my roommate's pc...

**Comment by ckulenkampff** [comment] 2019-10-29 13:30
@ludanxer as @quanzaiyu stated the workaround with `--temp .temp` does only work for some configuration points: 

> It takes effect when I changed some dynamically configurations, but changing fontmatter didn't work.

**Comment by hyvyys** [comment] 2020-02-13 16:59
Any updates on this? This is very irritating if you're trying to use vuepress to something beyond docs.

**Comment by egakupi** [comment] 2020-04-07 17:17
`vuepress dev --no-cache` helped me

**Comment by weishell** [comment] 2020-04-27 07:42
The menu bar on the left side of the second level title and the third level title will not be updated now

**Comment by 307590317** [comment] 2020-05-13 03:02
I meet the same problems in lastet version 1.5. Why hasn't this problem been solved？It has affected everyday use.I just want to have a normal incremental compilation and hot reload.

**Comment by pepsifan** [comment] 2020-05-17 19:38
Instead to `ctrl+c` and restart vuepress manually you can use [nodemon](https://github.com/remy/nodemon) to automate the restart on every file change.

- `npm i -D nodemon`
- Add to the `scripts` block in `package.json`:
`"start": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev"`
- Start vuepress with `npm start`

After a change in `.vue` or `.md` files the `vuepress dev` command will be executed. The changes can be seen after a browser refresh.

**Comment by qiuzhongrun** [comment] 2020-05-19 13:48
> Instead to `ctrl+c` and restart vuepress manually you can use [nodemon](https://github.com/remy/nodemon) to automate the restart on every file change.
> 
> * `npm i -D nodemon`
> * Add to the `scripts` block in `package.json`:
>   `"start": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev"`
> * Start vuepress with `npm start`
> 
> After a change in `.vue` or `.md` files the `vuepress dev` command will be executed. The changes can be seen after a browser refresh.

此方法有效，不过要注意最后的启动命令是vuepress dev doc
this works for me, but pay attention to the final start cmd `vuepress dev doc`

**Comment by hdodov** [comment] 2020-06-15 07:53
Using `1.5.1` and I have the same problems. When I change `.vuepress/config.js`, nothing happens.

**Comment by surjithctly** [comment] 2020-07-17 11:48
This issue is opened in *2019* and its still open. Where are the Core Team?

Its not a small issue. It really affects the Development. 

cc: @yyx990803 @ulivz @kefranabg @f3ltron @billyyyyy3320

**Comment by sdwru** [comment] 2020-07-17 15:13
> This issue is opened in **2019** and its still open. Where are the Core Team?
> 
> Its not a small issue. It really affects the Development.
> 
> cc: @yyx990803 @ulivz @kefranabg @f3ltron @billyyyyy3320

I agree, this is actually kind of a showstopper issue as far as I'm concerned.

**Comment by sdwru** [comment] 2020-07-17 15:22
> * "start": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev doc"

This doesn't work for me.  It restarts but the menu still doesn't get loaded.  I've tried all the supposed fixes I have found on the issues.  Only solution is stopping then starting `vuepress dev doc`

**Comment by jemerald** [comment] 2020-07-20 03:56
@sdwru add `js` to the list of extensions if you want `nodemon` to restart the vuepress dev server when you change the config file.

i.e.

```
"start": "nodemon --ext md,vue,js --watch .vuepress --watch . --exec vuepress dev doc"
```

**Comment by lipecss** [comment] 2020-07-24 20:03
im still getting `warning Override existing page` on console And the browser does not automatically update

**Comment by bencodezen** [comment] 2020-08-17 15:17
Hey everyone. Sorry for the delay on this. 

I've been testing this on v1.5.3 and on both Node v12 and v10 and it looks like it's resolved. 🎉 

If anyone is still encountering this, please re-open the issue and let me know what environment you're on and hopefully a repo I can clone to help debug.

**Closed by bencodezen** 2020-08-17 15:17 UTC
Labels: contribution welcome, priority: high, topic: config, type: bug

**Comment by damiansire** [comment] 2020-09-05 03:39
> Hey everyone. Sorry for the delay on this.
> 
> I've been testing this on v1.5.3 and on both Node v12 and v10 and it looks like it's resolved. 
> 
> If anyone is still encountering this, please re-open the issue and let me know what environment you're on and hopefully a repo I can clone to help debug.

Hi @bencodezen,

I used ubuntu and  have the same bug in     "vuepress": "^1.5.3" and node v12.13.1

**Comment by electric-skeptic** [comment] 2020-09-08 15:02
I still have this problem too.

- VuePress 1.5.3 & 1.5.4
- Node 14.2
- Windows 10

It's not so cumbersome to restart the dev server, a hotkey helps, but for the sake of speed [VitePress](https://github.com/vuejs/vitepress#wip-vitepress-) looks like it's becoming a terrific alternative! It is comparatively minimalistic and may not be stable yet.

**Comment by Akryum** [comment] 2021-01-05 15:26
Also seeing this issue with `sidebar: auto` in a md file.

**Comment by sundayz** [comment] 2021-01-05 15:32
People are still reporting this issue (#2392). Hot reloading development does not work for me out of the box (Windows 10, Node 12, VuePress 1.7.1)

`npm vuepress dev docs --temp .temp`

This fixed it for me. So it looks like something is wrong with the watchOptions.ignore config here? https://github.com/vuejs/vuepress/commit/7e9d0c1f42196dee52daabfaf796e0cdaa7bd6eb

From what I remember webpack watch doesn't really like Window style path separators `\\`, maybe that's why setting a custom temp directory path fixes it. It must be somehow passing in a path with \ separators?

@bencodezen Maybe this issue should be reopened.

**Comment by meteorlxy** [comment] 2021-01-07 07:09
If you are not strictly using vue 2, try [vuepress 2](https://github.com/vuepress/vuepress-next) or [vitepress](https://github.com/vuejs/vitepress).

**Comment by zhoufanglu** [comment] 2021-01-15 06:07
> > Instead to `ctrl+c` and restart vuepress manually you can use [nodemon](https://github.com/remy/nodemon) to automate the restart on every file change.
> > 
> > * `npm i -D nodemon`
> > * Add to the `scripts` block in `package.json`:
> >   `"start": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev"`
> > * Start vuepress with `npm start`
> > 
> > After a change in `.vue` or `.md` files the `vuepress dev` command will be executed. The changes can be seen after a browser refresh.
> 
> 此方法有效，不过要注意最后的启动命令是vuepress dev doc
> this works for me, but pay attention to the final start cmd `vuepress dev doc`

这是正确的方法。希望他们的方法能帮助你们。
This is the right approach.I hope their methods will help you.

**Comment by hyvyys** [comment] 2021-01-22 18:18
Still have this issue (both with config.js and frontmatter in the .md's) and the workaround from @sundayz does not work for me. On vuepress 1.8.0 (on Windows 10, if that matters). I might give vuepress-next a try though...

**Comment by sundayz** [comment] 2021-01-22 18:20
Does anyone know if vuepress 2 as mentioned by @meteorlxy is usable or if its just an alpha? And what exactly is vitepress, I'm not sure on the difference between vuepress and vitepress.

**Comment by hyvyys** [comment] 2021-01-22 18:43
Repo with replication: https://github.com/hyvyys/vuepress-frontmatter-hotreload-test

Replicate video: https://user-images.githubusercontent.com/20814638/105531681-fc99b800-5ce9-11eb-8c1f-fc0129629604.mp4
