### ISSUE TITLE
@vuepress/plugin-blog: documentation or lack thereof

### ISSUE THREAD

**Issue by mbana** [vuejs/vuepress#1229] opened 2019-01-25 21:13 UTC
https://vuepress.vuejs.org/plugin/official/plugin-blog.html

Aside from the installation instructions and a how-to-use guide there is hardly any information on this plugin.

* What does it do?
* Is there an example I can see of what it does?
* No example on how to set `postsDir`, `categoryIndexPageUrl`.

Don't take this negatively, but the page leaves one confused.

**Comment by Laruxo** [comment] 2019-01-25 22:01
From notice in VuePress page:
> Note that this is the document of 1.x, since it's still in alpha stage and things may change or break until we reach beta phase...

For the same reason there is no documentation yet. I think there are already quite a lot of issues related to docs.

If you need any help, I can help you out. I am trying out this plugin myself and it is quite simple if you read the source.

**Comment by ulivz** [comment] 2019-01-26 12:03
Thanks, but it's duplicate of https://github.com/vuejs/vuepress/issues/1091.

**Closed by ulivz** 2019-01-26 12:03 UTC

**Comment by songololo** [comment] 2019-02-21 19:42
A simple example would really help. Right now not at all sure how to get the blog component up and running.
