### ISSUE TITLE
Error installing global installation using yarn (works with npm)

### ISSUE THREAD

**Issue by ferry77** [vuejs/vuepress#103] opened 2018-04-17 12:07 UTC
I am on macOS with node v8.9.1

I followed Getting Started guide
``` bash
# install globally
yarn global add vuepress # OR npm install -g vuepress

# create a markdown file
echo '# Hello VuePress' > README.md

# start writing
vuepress dev
```

Got this error

``` bash
❯ yarn global add vuepress
yarn global v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "vuepress@0.5.1" with binaries:
      - vuepress
✨  Done in 44.55s.

❯ echo '# Hello VuePress' > README.md

❯ vuepress dev

  VuePress dev server listening at http://localhost:8080/

✖ ｢wdm｣: Hash: 1abc5370106edbc36ca1
Version: webpack 4.5.0
Time: 11435ms
Built at: 2018-4-17 21:34:41
           Asset       Size  Chunks             Chunk Names
assets/js/app.js   28.7 KiB     app  [emitted]  app
      index.html  320 bytes          [emitted]
Entrypoint app = assets/js/app.js
   [0] multi /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js 28 bytes {app} [built]
   [1] multi webpack-hot-client/client?12a67476-a472-4e30-a6d3-d9be688b817f /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js 40 bytes {app} [built]

ERROR in multi /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
Module not found: Error: Can't resolve 'buble-loader' in '/Users/xxxxxxx/Sites/vuepress'
 @ multi /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js

ERROR in multi webpack-hot-client/client?12a67476-a472-4e30-a6d3-d9be688b817f /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
Module not found: Error: Can't resolve 'buble-loader' in '/Users/xxxxxxx/Sites/vuepress'
 @ multi webpack-hot-client/client?12a67476-a472-4e30-a6d3-d9be688b817f /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js

ERROR in multi webpack-hot-client/client?12a67476-a472-4e30-a6d3-d9be688b817f /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
Module not found: Error: Can't resolve 'webpack-hot-client/client?12a67476-a472-4e30-a6d3-d9be688b817f' in '/Users/xxxxxxx/Sites/vuepress'
 @ multi webpack-hot-client/client?12a67476-a472-4e30-a6d3-d9be688b817f /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.38 MiB       0
    Entrypoint undefined = index.html
    [../../.config/yarn/global/node_modules/lodash/lodash.js] /Users/xxxxxxx/.config/yarn/global/node_modules/lodash/lodash.js 527 KiB {0} [built]
    [../../.config/yarn/global/node_modules/vuepress-html-webpack-plugin/lib/loader.js!../../.config/yarn/global/node_modules/vuepress/lib/app/index.dev.html] /Users/xxxxxxx/.config/yarn/global/node_modules/vuepress-html-webpack-plugin/lib/loader.js!/Users/xxxxxxx/.config/yarn/global/node_modules/vuepress/lib/app/index.dev.html 454 bytes {0} [built]
    [../../.config/yarn/global/node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
  [21:37:27] ✔ successfully compiled.
✖ ｢wdm｣: Hash: e3afee2caab7c3f1eb9f
```

Then I tried another path using npm surprisingly no error

``` bash
❯ yarn global remove vuepress
yarn global v1.3.2
[1/2] Removing module vuepress...
[2/2] Regenerating lockfile and installing missing dependencies...

success Uninstalled packages.
✨  Done in 1.80s.

~
❯ vuepress
zsh: command not found: vuepress

~
❯ npm install -g vuepress
/Users/ferry/.nvm/versions/node/v8.9.1/bin/vuepress -> /Users/ferry/.nvm/versions/node/v8.9.1/lib/node_modules/vuepress/bin/vuepress.js

> fsevents@1.1.3 install /Users/ferry/.nvm/versions/node/v8.9.1/lib/node_modules/vuepress/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ferry/.nvm/versions/node/v8.9.1/lib/node_modules/vuepress/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ vuepress@0.5.1
added 1087 packages in 28.643s

❯ vuepress dev

  VuePress dev server listening at http://localhost:8082/
```

Open http://localhost:8082/ chrome  successfully showing "Hello VuePress"

note: upgrading yarn to v1.6.0 doesn't help.

Happy to provide further info if required

Thanks!

**Comment by ferry77** [comment] 2018-04-17 12:11
sorry.. I just saw another post having the same [issue](https://github.com/vuejs/vuepress/issues/102)

**Comment by yyx990803** [comment] 2018-04-17 13:31
Closing as duplicate of #102

**Closed by yyx990803** 2018-04-17 13:31 UTC
