### ISSUE TITLE
 Nested sidebar groups support

### ISSUE THREAD

**Issue by 9-nine** [vuejs/vuepress#783] opened 2018-08-30 03:43 UTC
#### What problem does this feature solve?
```
sidebar: {
            '/foo/': [{
                title: 'parent',
                children: [{
                    title: 'child',
                    children: [
                        'bar/01',
                        'bar/02',
                        'bar/03'
                    ]
                }]
            }]
        },
```

Nested sidebar groups can not support.I want get this feature.Thanks!

**Comment by ulivz** [comment] 2018-08-30 15:54
Duplicate of https://github.com/vuejs/vuepress/issues/287 and closing it in favor of this PR: https://github.com/vuejs/vuepress/pull/669

**Closed by ulivz** 2018-08-30 15:54 UTC
Labels: duplicate
