### ISSUE TITLE
Unknown custom element: <v-xxxxxxx>

### ISSUE THREAD

**Issue by zhixinpeng** [vuejs/vuepress#2139] opened 2020-01-20 08:58 UTC
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

.vuepress/theme/Layout.vue

```html
<template>
  <div>
    <router-link to="/a">to a</router-link>
    <router-link to="/b">to b</router-link>
    <Content></Content>
  </div>
</template>
```

./a.md

```html
# a
```

./b.md

```html
# a
```

#### What is expected?

correct render

#### What is actually happening?

The first page I went to can render correctly, when I click link,The following error occurred

![image](https://user-images.githubusercontent.com/24643457/72712832-d311f200-3ba6-11ea-96b8-20e90460d9e7.png)

#### Other relevant information

- vuepress version: 1.2.0
- node version: 12.7.0

**Comment by vvni** [comment] 2020-01-20 15:05
这个问题我也遇到了，看到之前修复过这个问题，但是为什么v1.2.0还有这个问题呢？

**Comment by Mister-Hope** [comment] 2020-01-22 10:04
I met this too, it seems that [commit 2a5980](https://github.com/vuejs/vuepress/commit/2a598006776dd8f6d7dc13e811f7bdc56281aa80) had solved this issue. Maybe we can figure out.

**Comment by ozguruysal** [comment] 2020-01-22 10:42
I've been having this issue and here are the steps to reproduce it in Chrome.

### Tested with
VuePress 1.2.0
Vue.js devtools 5.3.3 

### Reproduction Steps
1. Run the project in `dev` mode.
2. Open it in browser in a fresh tab.
3. Open Chrome dev tools but only go to **Console** tab.
4. Navigate between routes `/route-a` and `route- b`. Everything works well, no errors.
5. Open **Vue** tab in Chrome dev tools to activate Vue.js devtools then go back to **Console** tab.
6. Now navigate to `/route-c` (i.e. any route you haven't yet visited) and you get the error.

Hope this helps anyone out there familiar with the codebase to identify the problem.

**Comment by Mister-Hope** [comment] 2020-01-23 06:02
> I've been having this issue and here are the steps to reproduce it in Chrome.
> 
> ### Tested with
> VuePress 1.2.0
> Vue.js devtools 5.3.3
> 
> ### Reproduction Steps
> 1. Run the project in `dev` mode.
> 2. Open it in browser in a fresh tab.
> 3. Open Chrome dev tools but only go to **Console** tab.
> 4. Navigate between routes `/route-a` and `route- b`. Everything works well, no errors.
> 5. Open **Vue** tab in Chrome dev tools to activate Vue.js devtools then go back to **Console** tab.
> 6. Now navigate to `/route-c` (i.e. any route you haven't yet visited) and you get the error.
> 
> Hope this helps anyone out there familiar with the codebase to identify the problem.

I am able to reproduce it, not surprice to find the official are keeping silence as they allways did.

**Comment by acmoles** [comment] 2020-01-23 09:55
I have also have this problem.

I don't experience the problem without following the Chrome repro steps, so, perhaps the issue relates to Vue devtools? Or the interaction between Vuepress and devtools?

**Comment by meteorlxy** [comment] 2020-01-30 19:58
@acmoles vue-devtools has some problems with dynamic components  https://github.com/vuejs/vue-devtools/issues/943 . Not sure if it's fixed

**Comment by meteorlxy** [comment] 2020-01-30 20:05
I cannot reproduce this issue without opening vue-devtools.

So this is a issue that comes from vue-devtools: https://github.com/vuejs/vue-devtools/issues/944

**Comment by meteorlxy** [comment] 2020-01-31 09:50
Closing this as this has been filed in https://github.com/vuejs/vue-devtools/issues/944.

Anyone else who encounter this problem, please check if it's related to your vue-devtools first.

**Closed by meteorlxy** 2020-01-31 09:50 UTC

**Comment by fsworld009** [comment] 2020-09-07 08:12
Get the same issue when trying to inheritance the default theme. This workaround works for me https://github.com/vuejs/vuepress/issues/1173#issuecomment-470534176
