### ISSUE TITLE
Make / unnecessary at the end of URLs

### ISSUE THREAD

**Issue by sergeyfilimonov** [vuejs/vuepress#931] opened 2018-10-14 17:05 UTC
## Feature request

There should be an option to remove / after a URL so that site.com/blog/ would look work as site.com/blog 

#### What problem does this feature solve?

It removes unnecessary and ugly slash after a URL.

#### What does the proposed API look like?

No idea.

#### How should this be implemented in your opinion?

It should be configured in config.js.

#### Are you willing to work on this yourself?**

I would wish to work on it but no as I am not qualified enough for this.

**Comment by martinsotirov** [comment] 2018-10-17 13:47
Not having a slash at the end would imply this is a file so that won't work in most browsers. You can either have "/blog/" or "/blog.html".

**Comment by sergeyfilimonov** [comment] 2018-10-17 14:44
> Not having a slash at the end would imply this is a file so that won't work in most browsers. You can either have "/blog/" or "/blog.html".

In most cases this is not the case. Actually I notice no slash in 99,9% of my web browsing experience. For instance, this issue has the URL https://github.com/vuejs/vuepress/issues/931 — no slash at the end.

**Comment by martinsotirov** [comment] 2018-10-17 14:59
When you're serving index.html files from nested directories, you automatically get a slash at the end. There are ways to configure your server to rewrite those requests but it's definitely not the default behavior. See [this](https://webmasters.stackexchange.com/questions/45267/removing-trailing-slash-for-sub-directory-url-indexing) for an Apache example.

In any case, this is beyond the scope of a static site generator in my opinion.

**Comment by sergeyfilimonov** [comment] 2018-10-17 15:19
> When you're serving index.html files from nested directories, you automatically get a slash at the end. There are ways to configure your server to rewrite those requests but it's definitely not the default behavior. See [this](https://webmasters.stackexchange.com/questions/45267/removing-trailing-slash-for-sub-directory-url-indexing) for an Apache example.
> 
> In any case, this is beyond the scope of a static site generator in my opinion.

Thanks! Didn't know about this. I guess Nginx works the same. Yes, it is unlikely about a site generator but let's give an opportunity to confirm this to someone else. If after a week the issue will not be replied I'll close it/

**Comment by ulivz** [comment] 2018-10-21 16:29
Thanks for your interest in VuePress, but it's duplicate of https://github.com/vuejs/vuepress/issues/603.

**Closed by ulivz** 2018-10-21 16:29 UTC
Labels: duplicate
