### ISSUE TITLE
Adding component does not work without restarting the server

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#346] opened 2018-05-05 19:29 UTC
- Your OS **Window**
- Node.js **8.4.0**
- VuePress **0.7.0**
- Browser version **Google Chrome Versión 66.0.3359.139 (Build oficial) (64 bits)**
- Is this a global or local install? **Global**
- Which package manager did you use for the install? **NPM**

When adding a new component it does not update me to be able to add it I have to restart the server and there is if it works well and finds the component

Example
```
.
└─ .vuepress
   └─ components
      ├─ demo-1.vue
      ├─ OtherComponent.vue
      └─ Demos  
           └─ Notifications
                 └─ The component is not yet added <---
```

I add it while the server is active

```
.
└─ .vuepress
   └─ components
      ├─ demo-1.vue
      ├─ OtherComponent.vue
      └─ Demos  
           └─ Notifications
                 └─ Prueba.vue <-- new component
```

And when adding the component in README.md it does not appear but after restarting the server of pueba if.

```
<Demos-Notifications-Prueba/>
```

![screenshot_32](https://user-images.githubusercontent.com/31676496/39666879-ccf26c62-5078-11e8-83cd-ccc2c7d5409f.png)

Every time I add a new component I have to restart the server? To make it work

**Comment by ulivz** [comment] 2018-05-06 17:42
Well, this is not a bug of VuePress, you should report it to `chokidar`.

But this issue, and #348, let me find a very interesting bug. 😄Thank you guys.

**Comment by ulivz** [comment] 2018-05-06 18:01
Closing is since I have created this interesting bug at: #351

**Closed by ulivz** 2018-05-06 18:01 UTC
Labels: enhancement
