### ISSUE TITLE
palette.style makes build error when update from alpha.27 to .30

### ISSUE THREAD

**Issue by chenweigao** [vuejs/vuepress#1133] opened 2018-12-25 06:26 UTC
There was something wrong when I updated the Vuepress to alpha.30, I don't know what is wrong until I **delete** the file `palette.styl`, I don't know why and is this a bug?

my repo is [there](https://github.com/chenweigao/vueblog), thank you very much.

**Comment by ulivz** [comment] 2018-12-25 16:08
> Q: Does new version make the custom color define unsupported?
> A: Noop.

I just cloned and test the build before and after the upgrade, and everything looks good to me. 



Closing this since it's a question and feel free to continue if it truly turns out to be a bug and you can provide an valid reproduction.

**Closed by ulivz** 2018-12-25 16:08 UTC
