### ISSUE TITLE
how can I dynamically reder some md content into cusomer theme (vue template)

### ISSUE THREAD

**Issue by lucky-yang** [vuejs/vuepress#2353] opened 2020-04-30 03:28 UTC
in one .vue file(component) of the theme, I just want to dynamically render some md content as below in to the .vue template

md content:
```
::: slot aaa
# Here is slot aaa
:::
- A Paragraph
- Another Paragraph
::: slot bbb
Here is slot bbb
:::
```
and vue theme template is like this:
```
<template>
  <div class="theme-container">
    <Content slot-key="aaa" />
   <br/>=============
    <Content />
   <br/>=============
    <Content slot-key="bbb" />
    <br />
  </div>
</template>
```
And the md content I can get it from some back-end api, I want to dynamically render it in the page, how can I do it.

Many thanks.

**Comment by fvanwijk** [comment] 2020-04-30 11:00
Duplicate of #2352

**Comment by lucky-yang** [comment] 2020-04-30 12:01
> Duplicate of #2352

Dear sir,
Could you please help me on this question? 
I know the markdown content in .md file is transform to html and then embed into the vue component at the compliing time.
But I want to do this similar thing dynamically on page.

Many thanks.

**Comment by ulivz** [comment] 2020-06-13 18:26
Duplicate of #2352

**Closed by ulivz** 2020-06-13 18:26 UTC
