### ISSUE TITLE
Uncaught SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by oyexiaozhi** [vuejs/vuepress#1559] opened 2019-04-25 04:28 UTC
- [ ] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.47
#### Steps to reproduce
1.according to the official website example
2.run command: npm run docs:dev

#### What is expected?
vuepress can work normally
#### What is actually happening?
Uncaught SyntaxError: Unexpected token (      in     util.js?e440:85
#### Other relevant information

- Your OS: windows
- Node.js version: 10.15.1
- Browser version: Chrome 53.0.2785.143 m
- Is this a global or local install? local install
- Which package manager did you use for the install?npm
- Does this issue occur when all plugins are disabled?yes

**Comment by oyexiaozhi** [comment] 2019-04-25 04:30
export function ensureAsyncComponentsLoaded (...names) {
  return Promise.all(names.filter(v => v).map(async (name) => {
    if (!getVueComponent(name) && getAsyncComponent(name)) {
      const comp = await getAsyncComponent(name)()
      Vue.component(name, comp.default)
    }
  }))
}

**Comment by timaschew** [comment] 2019-04-25 21:41
This seems to be not a VuePress issue.

Anyhow, please include a minimal reproduction using e.g. CodeSandbox, CodePen, or a GitHub repository.

**Comment by oyexiaozhi** [comment] 2019-04-29 02:11
Okay.
It should not be a problem with VuePress.
I found this problem only appears in lower versions of Google Chrome.

**Comment by ulivz** [comment] 2019-05-01 05:22
Closing this since it doesn't provide any valid repro repo and would not be a issue of VuePress.

**Closed by ulivz** 2019-05-01 05:22 UTC
