### ISSUE TITLE
Expansion and fold of the block of code

### ISSUE THREAD

**Issue by RonaldZhao** [vuejs/vuepress#432] opened 2018-05-12 16:30 UTC
希望能够增加代码块的展开和收起功能，因为在有些文章中引用到的代码有时候比较多，而且比较长，所以导致文章会显得特别长，容易造成读者心理上的排斥感，所以希望有此功能可以让读者遇到这种文章的时候可以逐步深入，自由展开与收起，提高用户体验。感谢~

**Comment by gaomd** [comment] 2018-05-15 04:43
Initially I think this feature is useless, but look at the [Vue Style Guide](https://vuejs.org/v2/style-guide/), it look great.

Since HTML are capabale of implementing this feature, I believe we should provide a default CSS and that's enough:

``` html
<details open="">
<summary>

#### Click to Toggle

</summary>

Lorem Ipsum Expanded

</details>
```

---

<details open="">
<summary>

#### Click to Toggle

</summary>

Lorem Ipsum Expanded

</details>

---

**Comment by RonaldZhao** [comment] 2018-05-15 05:07
thanks, boi. i will try it and i think that's what i need.

**Comment by RonaldZhao** [comment] 2018-05-15 05:26
so i must add it in every code block?or there is another way i do not konw?
i use it like this:
`
<details>

<summary>我的解法</summary>

```python
def feast(beast, dish):
    # 解法一
    return beast[0] == dish[0] and beast[-1] == dish[-1]
	# 解法二：return beast.startswith(dish[0]) and beast.endswith(dish[-1])
```

</details>
`

**Comment by ulivz** [comment] 2018-08-20 11:15
Duplicate of #408.

**Closed by ulivz** 2018-08-20 11:15 UTC
Labels: duplicate
