### ISSUE TITLE
TypeError: renderChildren(...) is not iterable

### ISSUE THREAD

**Issue by anishkny** [vuejs/vuepress#34] opened 2018-04-15 02:34 UTC
Repro:

```bash
git clone https://github.com/anishkny/vuepress-base
cd vuepress-base
npm i
npm run build
```

Error:
```
npm run build

> vuepress-base@1.0.0 build /Users/anish/playground/vuepress-base
> vuepress build


Rendering static HTML...
Rendering page: /Error rendering /:
TypeError: renderChildren(...) is not iterable
    at children.map.c (server-bundle.js:2005:10)
    at Array.map (<anonymous>)
    at renderChildren (server-bundle.js:2001:61)
    at render (server-bundle.js:1978:21)
    at renderWithStyleInjection (server-bundle.js:195:16)
    at createFunctionalComponent (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:1944:521
    at VueComponent.renderList [as _l] (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.Sidebarvue_type_template_id_5e11e29e_render (server-bundle.js:1944:258)
    at VueComponent.Vue._render (/Users/anish/playground/vuepress-base/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/Users/anish/playground/vuepress-base/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/Users/anish/playground/vuepress-base/node_modules/vue-server-renderer/build.js:7491:5)

Success! Generated static files in .vuepress/dist.
```

The site does get generated, but upon loading get console error in browser:
```
app.f38efceb.js:8 TypeError: Ma(...) is not a function or its return value is not iterable
    at Ma.e.map.e (app.f38efceb.js:13)
    at Array.map (<anonymous>)
    at Ma (app.f38efceb.js:13)
    at render (app.f38efceb.js:13)
    at app.f38efceb.js:8
    at rn (app.f38efceb.js:8)
    at app.f38efceb.js:8
    at sn (app.f38efceb.js:8)
    at t._c (app.f38efceb.js:8)
    at app.f38efceb.js:13
Ft @ app.f38efceb.js:8
127.0.0.1/ Failed to load resource: the server responded with a status of 404 (Not Found)
```

I am on MacOS Sierra 10.12.6, Node v8.9.4, npm v5.6.0.

**Comment by yyx990803** [comment] 2018-04-15 02:54
Can't reproduce but should be fixed in 42f63a8

**Closed by yyx990803** 2018-04-15 02:54 UTC
