### ISSUE TITLE
Using code block inside of HTML content breaks template parsing

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vuepress#622] opened 2018-06-29 09:47 UTC
## Bug report

Using code block inside of HTML content breaks template parsing (in this case causes compiler to misinterpret it as missing closing tags errors)

#### Version

`v0.10.2`

#### Steps to reproduce

Create page with content:
```
<dl class="pon-faq" id="pon-faq11">
   <dt>Can I disable or hide some sections and screens from the theme settings?</dt>
   <dd>
	``` php
        apply_filters( 'wp_init', function(){
        	return;
        } );
	```
       <p>Yes, you can easily do so in a [child theme](/ponteus/getting-started-child-theme/) using filter. Please keep in mind that this will block your users from making some configuration changes and will affect functionalities.</p>
   </dd>
</dl>
```
#### What is expected?
Code block should be parsed correctly (generating highlighted code block as a result) as well as HTML template parsing should not break.

#### What is actually happening?

I'm getting template errors (after removing the problematic code block all the errors disappear):
`Error compiling template`
` - tag <dd> has no matching end tag.`

**Comment by ulivz** [comment] 2018-07-01 07:45
See: https://github.com/vuejs/vuepress/issues/619#issuecomment-401589883

Duplicate of #619.

Workaround:

```` html
<dl class="pon-faq" id="pon-faq11">
   <dt>Can I disable or hide some sections and screens from the theme settings?</dt>
   <dd>

``` php
      apply_filters( 'wp_init', function(){
        return;
      } );
```
       <p>Yes, you can easily do so in a [child theme](/ponteus/getting-started-child-theme/) using filter. Please keep in mind that this will block your users from making some configuration changes and will affect functionalities.</p>
   </dd>
</dl>
````

**Closed by ulivz** 2018-07-01 07:45 UTC
