### ISSUE TITLE
Add Copy Code button and Back to top button

### ISSUE THREAD

**Issue by revolveyao** [vuejs/vuepress#809] opened 2018-09-07 02:31 UTC
## Feature request
Add Copy Code button and Back to top button

#### What problem does this feature solve?
The Copy Code button is used to copy the code block
The back to the top button is used to easily return to the top of the page
#### What does the proposed API look like?
Set inside the Config.js
#### How should this be implemented in your opinion?
I do not know
#### Are you willing to work on this yourself?**
I can‘t use JavaScript.

**Comment by ulivz** [comment] 2018-09-07 02:41
Duplicate of https://github.com/vuejs/vuepress/issues/703
And `Back to top` has been finished in the [next](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-back-to-top) branch.

**Closed by ulivz** 2018-09-07 02:41 UTC
Labels: duplicate
