### ISSUE TITLE
Vuepress vue-router issue

### ISSUE THREAD

**Issue by davidcraig** [vuejs/vuepress#728] opened 2018-08-11 19:11 UTC
#### Version
0.14.1

#### Steps to reproduce

dev/build
attempt to click navigation item

#### What is expected?

route is followed

#### What is actually happening?

error in console (Varies depending on whether dev or build)

##### Dev browser console output

```
TypeError: "Object(...) is not a function"
mountedwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\cache-loader\dist\cjs.js?!C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\babel-loader\lib\index.js?!C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-loader\lib\index.js?!./.vuepress/theme/Layout.vue?vue&type=script&lang=js&:124:91iteratorwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1944:7stepwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1718:9stepwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1719:11iteratorwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1965:11createAppwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vuepress\lib\app\app.js:97:7iteratorwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1944:7stepwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1718:9stepwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1722:9runQueuewebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1726:3confirmTransitionwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1973:3transitionTowebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:1875:3pushwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:2182:5pushwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:2535:3handlerwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue-router\dist\vue-router.esm.js:445:11invokerwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue\dist\vue.runtime.esm.js:2022:14_withTaskwebpack-internal:///C:\Users\david\AppData\Local\Yarn\Data\global\node_modules\vue\dist\vue.runtime.esm.js:1821:15
```

##### Build browser console output

```
app.90372091.js:8 TypeError: (void 0) is not a function
    at app.90372091.js:8
    at f (app.90372091.js:8)
    at r (app.90372091.js:8)
    at app.90372091.js:8
    at app.90372091.js:8
    at app.90372091.js:8
    at f (app.90372091.js:8)
    at r (app.90372091.js:8)
    at r (app.90372091.js:8)
    at ji (app.90372091.js:8)
i @ app.90372091.js:8
f @ app.90372091.js:8
r @ app.90372091.js:8
(anonymous) @ app.90372091.js:8
(anonymous) @ app.90372091.js:8
(anonymous) @ app.90372091.js:8
f @ app.90372091.js:8
r @ app.90372091.js:8
r @ app.90372091.js:8
ji @ app.90372091.js:8
Ri.confirmTransition @ app.90372091.js:8
Ri.transitionTo @ app.90372091.js:8
e.push @ app.90372091.js:8
Ki.push @ app.90372091.js:8
m @ app.90372091.js:8
e @ app.90372091.js:3
t._withTask.t._withTask @ app.90372091.js:3
```

#### Other relevant information

- Your OS: Windows
- Node.js version: 8.11.3
- Browser version: Chrome 68 / Firefox 61
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

**Comment by davidcraig** [comment] 2018-08-11 19:13
Site I am experiencing issue on is here: https://inglorious-blasters.gitlab.io/  actual source code is currently in a gitlab private repo but I can share if this would be helpful, it seemed to build ok on mac on my last build, perhaps this is a quirk of windows?

**Comment by ulivz** [comment] 2018-08-11 19:43
I'll appreciate if you take the time to create a minimal reproduction repo by [template-vuepress](https://github.com/ulivz/template-vuepress).

**Comment by davidcraig** [comment] 2018-08-11 19:48
Hi,

I have just renamed the .vuepress/theme folder as I did previous eject the theme and make very minor modifications, it seems to be working correctly now although I need to do some restyling.

**Comment by ulivz** [comment] 2018-08-11 20:00
Closing since it seems to be a issue introduced by your modifications. If it turns out to be a bug of VuePress, feel free to reopen it.

**Closed by ulivz** 2018-08-11 20:00 UTC
Labels: need repro
