### ISSUE TITLE
Allow excluding specific entries from the scripts section

### ISSUE THREAD

**Issue by sergeymorkovkin** [vuejs/vuepress#1638] opened 2019-06-03 12:04 UTC
#### What problem does this feature solve?

In current implementation all generated entries are included into the scripts section and there is no ability to change this.

#### What does the proposed API look like?

The `excludeEntries` configuration property containing an array of entry files.

#### How should this be implemented in your opinion?

Straightforward, by should consider both dev server and build SSR.

#### Are you willing to work on this yourself?

Yes if you confirm this is welcome.

**Comment by newsbielt703** [comment] 2020-01-30 16:39
Apologies for the delayed response. Close it as a duplicate of #1558.

**Closed by newsbielt703** 2020-01-30 16:39 UTC
