### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/es6.array.index-of'

### ISSUE THREAD

**Issue by j710328466** [vuejs/vuepress#1605] opened 2019-05-17 09:51 UTC
- [ ] I confirm that this is an issue rather than a question.

#### What is expected?

it work normally, and show the home page like it before

#### What is actually happening?

page is blank, and console throw some error, like this:

client?46a1:209 ./node_modules/_@vuepress_plugin-search@1.0.0-alpha.48@@vuepress/plugin-search/SearchBox.vue?vue&type=script&lang=js& (./node_modules/_cache-loader@3.0.1@cache-loader/dist/cjs.js??ref--3-0!./node_modules/_babel-loader@8.0.6@babel-loader/lib??ref--3-1!./node_modules/_cache-loader@3.0.1@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.0@vue-loader/lib??vue-loader-options!./node_modules/_@vuepress_plugin-search@1.0.0-alpha.48@@vuepress/plugin-search/SearchBox.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'core-js/modules/es6.array.index-of' in '/Users/mac/Desktop/workspace/JIMI/public-tools/node_modules/_@vuepress_plugin-search@1.0.0-alpha.48@@vuepress/plugin-search'

#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: ^1.0.0-alpha.48
  - OS: 10.14.4
  - Node.js version: 11.10.1 
  - Browser version: 74.0.3729.157
  - Is this a global or local install? local
  - Which package manager did you use for the install? npm
  - Does this issue occur when all plugins are disabled? i dont know

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.5
    Safari: 12.1
  npmPackages:
    @vuepress/core:  1.0.0-alpha.48 
    @vuepress/theme-default:  1.0.0-alpha.48 
    vuepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48 
  npmGlobalPackages:
    vuepress: Not Found

**Comment by hzgotb** [comment] 2019-05-20 14:55
把node_modules删除，重新 install 一下

**Comment by jledentu** [comment] 2019-09-02 11:53
Hi,

This is a duplicate of https://github.com/vuejs/vuepress/issues/1529.
I had the same error with `vuepress@1.03` and an older version of `@vue/babel-preset-app`. As suggested in the other issue, I resolved by installing a newer `@vue/babel-preset-app`:

```
yarn add -D @vue/babel-preset-app
```

**Comment by f3ltron** [comment] 2019-09-05 14:06
As the solution is working i am clonsing this issue. Thank's for your question @j710328466 feel free to re open if it's not working

**Closed by f3ltron** 2019-09-05 14:06 UTC
