### ISSUE TITLE
Underscores in section title ignored in TOC

### ISSUE THREAD

**Issue by Benjamin-Lee** [vuejs/vuepress#2026] opened 2019-11-15 19:58 UTC
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Create a file with a section named `foo_bar_baz` and note that the TOC shows it as `foobarbaz`.

This is closely related to #544.

#### What is expected?

In the sidebar, the section title should be `immediate_command_async`, which is the name of the function.

#### What is actually happening?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/13618205/68971577-cf817980-07b7-11ea-9de5-ceb96a02ca27.png">

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: Not Found
    Safari: 13.0.3
  npmPackages:
    @vuepress/core:  1.0.2
    @vuepress/theme-default:  1.0.2
    vuepress:  1.0.2
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ludanxer** [comment] 2019-11-16 03:14
Hi @Benjamin-Lee ,

I'm sorry I can't reproduce your problem, do I miss anything?

My reproduction:
- [repo > underscore branch](https://github.com/ludanxer/vuepress-support/tree/underscore)
- [deployment](https://vuepress-support-git-underscore.ludanxer.now.sh)

My suggestions are:
1. Upgrade your Vuepress to the latest version `1.2.0`
2. Add `\` before `_` as #544 suggested

**Comment by kefranabg** [comment] 2019-11-22 14:49
@Benjamin-Lee I'll close the issue for now. Feel free to comment if the answer didn't solve your problem.

**Closed by kefranabg** 2019-11-22 14:49 UTC
