### ISSUE TITLE
vue-cli项目中不能启动vuepress

### ISSUE THREAD

**Issue by zouqilai** [vuejs/vuepress#1070] opened 2018-12-05 09:33 UTC
vue-cli搭建的项目
npm install -D vuepress
mkdir docs
echo '# Hello VuePress!' > docs/README.md
npm run docs:dev

启动时报错
![image](https://user-images.githubusercontent.com/10055439/49504263-45951500-f8b4-11e8-8203-c474cea38f4d.png)
更新过vue-loader,仍然不管用

**Comment by ulivz** [comment] 2018-12-25 16:43
To report an issue that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. [vuepress-issue-example](https://github.com/ocavue/vuepress-issue-example)), otherwise I don't know where you are going wrong.

**Comment by ulivz** [comment] 2018-12-25 16:46
Duplicate of https://github.com/vuejs/vuepress/issues/900, let's move here to continue.

**Closed by ulivz** 2018-12-25 16:46 UTC
Labels: need reproduction repo

**Comment by Jimmy0w0** [comment] 2019-01-28 05:20
是否有设置好package.json
在里面添加script？
