### ISSUE TITLE
Support of "sidebarDepth: 3"

### ISSUE THREAD

**Issue by YGYOOO** [vuejs/vuepress#1715] opened 2019-07-24 09:31 UTC
## Feature request
Now the max value of `sidebarDepth` is 2, could you support 3?

#### What problem does this feature solve?
In some cases, only 2 levels may not meets the needs.

#### What does the proposed API look like?
`sidebarDepth: 3`

#### How should this be implemented in your opinion?
I think extracting h4 would be similar with extracting h2 and h3. It may not be hard to be implemented.

#### Are you willing to work on this yourself?
Currently not.

**Comment by ulivz** [comment] 2019-07-28 18:27
Duplicate of #984

**Closed by ulivz** 2019-07-28 18:27 UTC

**Comment by kshefchek** [comment] 2020-08-19 18:35
According to the docs this has not been added, and it not covered by #984 or PR #1945, please consider reopening
