### ISSUE TITLE
heroImage should be responsive

### ISSUE THREAD

**Issue by chrtz** [vuejs/vuepress#503] opened 2018-05-25 14:40 UTC
## Feature request
As you can add a heroImage to pages via YAML:
```
---
home: true
heroImage: /your-hero-image.png
---
```
(btw. there should be a notice in the docs, that the image has to be in `.vuepress/public/`.)

The chosen image should be responsive as the rest of the page.
If you resize the page, the image stays in its original dimension.

#### What problem does this feature solve?
Makes the heroImage responsive.

#### How should this be implemented in your opinion?
```
   .hero > img {
        max-width: 100%;
        height: auto;
        overflow: hidden;
        }
```
quick and dirty, this could be added to `/default-theme/styles/theme.styl`.

#### Are you willing to work on this yourself?**
In my case I gave the root `README.md` a **pageClass** via **YAML** and added a custom CSS to the `override.styl`.

**Comment by ulivz** [comment] 2018-05-27 10:09
Closing since this pull request doesn't provide a proper reproduction repository / link.

**Comment by chrtz** [comment] 2018-05-27 10:12
Didn't saw the need for a repo, as I provided a explanation plus source code example to reproduce.

**Comment by ulivz** [comment] 2018-05-27 10:35
If you expect others to read your description and give you a answer, first, you should treasure the description you gave.

![image](https://user-images.githubusercontent.com/23133919/40584870-759df458-61db-11e8-9631-98c6f35e1dc6.png)

To be honest, I was very upset when I saw such a format. It makes me think you just want to throw away a problem to others. 

Back to the issue itself, PR welcome.

**Comment by ulivz** [comment] 2018-05-27 16:37
As you said, you can can use `pageClass` and `override.styl` to get it.

We don't plan to make the hero image leverage `max-width: 100%` since in default theme it should be `max-height 280px`. so this feature should be done in userland.

**Closed by ulivz** 2018-05-27 16:37 UTC

**Comment by chrtz** [comment] 2018-05-28 11:32
EDIT: I just saw that there is a notice in the docs for static assets to be stored in `.vuepress/public`.
