### ISSUE TITLE
After build vuepress projects can't find assets

### ISSUE THREAD

**Issue by cihanzengin** [vuejs/vuepress#701] opened 2018-08-06 12:02 UTC
Hello, after build the vuepress projects in dist folder index html can't access to assets folder

i think it's problem with webpack actually but where and how fix it 
so src files i think need to be like that **'assets/js'** not **'/assets/js'**

**Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/2.861402b7.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/3.d3286b67.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/4.9cb36c0a.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/7.30e4cee6.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/8.3a7bf2d5.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/9.7a656a02.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/10.64d70917.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/js/11.ba9c93f4.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)**

**Comment by ulivz** [comment] 2018-08-07 15:06
Duplicate of #667

See: https://github.com/vuejs/vuepress/issues/667#issuecomment-407704352

**Closed by ulivz** 2018-08-07 15:06 UTC
