### ISSUE TITLE
Allow output page extension to be .htm instead of .html

### ISSUE THREAD

**Issue by chengyuhui** [vuejs/vuepress#2424] opened 2020-06-04 08:55 UTC
#### What problem does this feature solve?
I am working on a site which, for some text filtering reason, requires `htm` instead of `html` as the
extension of output HTML pages. `vuepress-plugin-clean-urls` kind of solves this problem by changing the output path, but internal links that ends with `.md` seems to be hardcoded to be replaced by `.html`, which is not ideal.
#### What does the proposed API look like?
Probably a option such as `htmlSuffix`, or a new plugin?
#### How should this be implemented in your opinion?
Same as above.
#### Are you willing to work on this yourself?
I am willing to try to work on this, but it seems that this is hardcoded in an unknown place (I tried debugging `@vuepress/markdown/lib/link.js`, but no breakpoint is hit.

**Comment by davidgiga1993** [comment] 2020-06-04 13:42
Duplicate of #2420

**Comment by billyyyyy3320** [comment] 2020-10-19 17:17
Thanks for the report. Going to trace the issue in #2452.

**Closed by billyyyyy3320** 2020-10-19 17:17 UTC
