### ISSUE TITLE
Exclude/include texts in Markdown via vuepress

### ISSUE THREAD

**Issue by Minhsh** [vuejs/vuepress#1949] opened 2019-10-14 03:54 UTC
Hi, I am working for a project that has different versions and likewise its documentation has different versions (with minor differences). We want to maintain single source Markdown and generate different html output to reduce the maintenance efforts. So, I am wondering if this is achievable with vuepress? Specifically is it possible to show/hide some texts in the html output generated by vuepress? Thanks!

**Comment by kefranabg** [comment] 2019-10-14 10:04
If you're talking about a versioning mechanism, this is a duplicate of #1018 .

FIY you can also customize VuePress with [theme inheritance](https://vuepress.vuejs.org/theme/inheritance.html). You can also use vue syntax within your markdown files, that combined with [`page` & `siteConfig` data](https://vuepress.vuejs.org/guide/using-vue.html#templating) maybe you could solve your problem.

Feel free to comment this post if I misunderstood something.

**Closed by kefranabg** 2019-10-14 10:04 UTC

**Comment by RayKimEX** [comment] 2020-06-29 05:47
Hi, I want to use this feature like [embed-files](https://docsify.js.org/#/embed-files) , not using [theme inheritance](https://vuepress.vuejs.org/theme/inheritance.html) and combiend with  [page & siteConfig data](https://vuepress.vuejs.org/guide/using-vue.html#templating). because [embed-files](https://docsify.js.org/#/embed-files) more maintainable than that you suggested @bencodezen @kefranabg @ulivz
