### ISSUE TITLE
Hot reload not working 

### ISSUE THREAD

**Issue by reiwa** [vuejs/vuepress#2392] opened 2020-05-18 02:02 UTC
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

```
$ yarn add vuepress --dev
$ mkdir docs
$ youch docs/index.md
$ yarn vuepress dev docs

success [08:52:12] Build 1d01b9 finished in 172 ms! ( http://localhost:8080/ )
```

#### What is expected?

Vuepress CLI detects file changes and rebuilds.

#### What is actually happening?

Vuepress CLI doesn't detect file changes. I have to run `vuepress dev docs` again to build codes.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
% npx vuepress info

Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.2.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.4 - ~/.nodebrew/current/bin/yarn
    npm: 6.14.4 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @vuepress/core:  1.5.0 
    @vuepress/theme-default:  1.5.0 
    vuepress: ^1.5.0 => 1.5.0 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by reiwa** [comment] 2020-05-18 02:19
https://github.com/vuejs/vue-loader/issues/1669

**Comment by iDerekLi** [comment] 2020-05-19 05:35
I have the same situation. After testing node v10.15.3 hot not working. Node v12.14.0 hot working

**Comment by xyyxlq** [comment] 2020-05-19 13:00
I have the same problem too.
When I change the content of .md files, the hot reload don't work, even the Vuepress CLI doesn't detect file changes.
I have tried with node v10.15.0 and node v12.16.3，but the hot still don't works。

**Comment by Karlbovsky** [comment] 2020-05-20 11:06
Same here, not sure if it´s related to the latest Node v12.16.3 upgrade I've made, since in some projects (with similar packages structure and same pkgs versions) hot reloading still works. Very confused atm...

**Comment by pepsifan** [comment] 2020-05-20 12:38
I had the same problems a few days ago. I use a workaround to restart the server on file change. See [here](https://github.com/vuejs/vuepress/issues/1283#issuecomment-629849407).

**Comment by 307590317** [comment] 2020-05-21 03:52
I have the same problems now. 
Currently, the best solution that does not affect normal use is to directly replace the previous whole ` node_modules`, then without npm install, and just `npm run dev` the project.
I used the vuepress 1.41 package I downloaded earlier, now node v12.16.3, hot reload working

**Comment by Yaakov-Belch** [comment] 2020-05-21 07:11
I tried vuepress 1.4.1 with node 12.16.3 with a new install now -- and it vuepress does not recognize document changes (hot reload does not work).  It looks like a regression in one of the dependencies --- so by loading the newer version of the dependency, the feature breaks.  I don't know what package is broken.

**Comment by Yaakov-Belch** [comment] 2020-05-21 07:35
It seems that in its dependency chain, vuepress uses outdated packages for `Chokidar` and `fsevents` that are responsible for watching file changes.

Here is my current install log:

```
warning vuepress > @vuepress/core > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning vuepress > @vuepress/core > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning vuepress > @vuepress/core > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning vuepress > @vuepress/theme-default > docsearch.js > hogan.js > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning vuepress > @vuepress/theme-default > docsearch.js > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning vuepress > @vuepress/core > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning vuepress > @vuepress/theme-default > stylus > css-parse > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning vuepress > @vuepress/core > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning vuepress > @vuepress/core > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```
As far as I see, the relevant messages are:

* `vuepress/core` and `webpack-dev-server` depend on `chokidar@2.1.8` with the warning: **Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.**
* `chokidar` depends on `fsevents@1.2.13` or `fsevents@2.1.3`.  Both of these package issue the warning **The platform "linux" is incompatible with this module.**  Quite possibly, chokidar uses other modules on the linux platform.

**Comment by pepsifan** [comment] 2020-05-21 08:00
As I can see, `chokidar` is only used for watching files which are added or deleted (see [source](https://github.com/vuejs/vuepress/blob/54b84b3a780785488c6a6f309f84dd720b872d51/packages/%40vuepress/core/lib/node/dev/index.js#L67)) and for changes in the config file (see [source](https://github.com/vuejs/vuepress/blob/54b84b3a780785488c6a6f309f84dd720b872d51/packages/%40vuepress/core/lib/node/dev/index.js#L85)). I rather think it's a problem with a loader for the webpack server which can't detect changes of `.md` and `.vue` files. The loaders are registered in [createBaseConfig.js](https://github.com/vuejs/vuepress/blob/54b84b3a780785488c6a6f309f84dd720b872d51/packages/%40vuepress/core/lib/node/webpack/createBaseConfig.js#L107).

**Comment by yangtao2o** [comment] 2020-05-22 02:48
> I have the same problems now.
> Currently, the best solution that does not affect normal use is to directly replace the previous whole ` node_modules`, then without npm install, and just `npm run dev` the project.
> I used the vuepress 1.41 package I downloaded earlier, now node v12.16.3, hot reload working

Yes, this way is currently the most effective，and wait for the latest version to deal with this problem.

I used the `vuepress v1.40`, and `node v14.2.0`, hot reload working.

And use `nodemon` to automate the restart on every file change. Thanks @pepsifan .
```shell
yarn add -D nodemon
```
```js
{
  "scripts": {
    "dev": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev docs",
  }
}
```

**Comment by 307590317** [comment] 2020-05-22 06:33
> I tried vuepress 1.4.1 with node 12.16.3 with a new install now -- and it vuepress does not recognize document changes (hot reload does not work). It looks like a regression in one of the dependencies --- so by loading the newer version of the dependency, the feature breaks. I don't know what package is broken.

Instead of using the previous version for a new install, you can simply copy the installed package from the previous version and launch the project. No new install is required

**Comment by fmonper1** [comment] 2020-05-23 00:07
Vuepress v1.4.0, hot reloading not working with node v14.3.0. Using nodemon isnt working either

**Comment by a616781689** [comment] 2020-05-24 04:42
me too

**Comment by qyingkou** [comment] 2020-05-24 13:25
follow bug fixes...

**Comment by faroit** [comment] 2020-05-24 13:27
is there any working workaround (I would be willing to downgrade to older versions)... when was this broken?

**Comment by kurotanshi** [comment] 2020-05-24 14:47
I have the same problem :(

**Comment by bencodezen** [comment] 2020-05-24 15:36
Thanks for filing the issue @reiwa! Going to take a look into this as a high priority. Appreciate it!

**Comment by changhighly** [comment] 2020-05-25 04:31
Although it works, I have to refresh my browser for it to work

**Comment by changhighly** [comment] 2020-05-25 04:32
> > I have the same problems now.
> > Currently, the best solution that does not affect normal use is to directly replace the previous whole ` node_modules`, then without npm install, and just `npm run dev` the project.
> > I used the vuepress 1.41 package I downloaded earlier, now node v12.16.3, hot reload working
> 
> Yes, this way is currently the most effective，and wait for the latest version to deal with this problem.
> 
> I used the `vuepress v1.40`, and `node v14.2.0`, hot reload working.
> 
> And use `nodemon` to automate the restart on every file change. Thanks @pepsifan .
> 
> ```shell
> yarn add -D nodemon
> ```
> 
> ```js
> {
>   "scripts": {
>     "dev": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev docs",
>   }
> }
> ```

Although it works, I have to refresh my browser for it to work

**Comment by SCWR** [comment] 2020-05-25 06:22
"watchpack": "1.6.1"
``` bash
npm i -D watchpack@1.6.1
```
I noticed that the webpack hot update plugin `watchpack` is now `1.7.2`
I compared the previous project and found it was `1.6.1`
So I tried to install this version
It's ready for hot update

**Comment by xyyxlq** [comment] 2020-05-25 08:00
@SCWR Thanks, it works.

**Comment by ansky-pro** [comment] 2020-05-25 17:06
Thanks to @SCWR I got it working by downgrading watchpack to 1.6.1
Added `resolutions` section to `package.json` and ran `yarn install`
```
  "resolutions": {
    "watchpack": "1.6.1"
  }
```
Hope this helps to anyone struggling with the same problem

**Comment by SCWR** [comment] 2020-05-26 02:08
> Thanks to @SCWR I got it working by downgrading watchpack to 1.6.1
> Added `resolutions` section to `package.json` and ran `yarn install`
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Hope this helps to anyone struggling with the same problem

I acquired new knowledge @ansky-pro  Thanks

**Comment by Loyz07** [comment] 2020-05-26 09:22
> > Thanks to @SCWR I got it working by downgrading watchpack to 1.6.1
> > Added `resolutions` section to `package.json` and ran `yarn install`
> > ```
> >   "resolutions": {
> >     "watchpack": "1.6.1"
> >   }
> > ```
> > 
> > 
> > Hope this helps to anyone struggling with the same problem
> 
> I acquired new knowledge @ansky-pro Thanks

Hello,

For those who still want to use npm (resolutions only works with yarn by default). You can use this package : https://github.com/rogeriochaves/npm-force-resolutions.

**Comment by pepsifan** [comment] 2020-05-26 10:37
I think, a good solution would be to commit the `package-lock.json` into the repo. So the users only have to `npm ci`. This will ensure that the deps are exactly the same like the ones defined in `package-lock.json`.

**Comment by morosefrog** [comment] 2020-05-28 02:25
> Thanks to @SCWR I got it working by downgrading watchpack to 1.6.1
> Added `resolutions` section to `package.json` and ran `yarn install`
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Hope this helps to anyone struggling with the same problem

Good job , Thinks

**Comment by spike31** [comment] 2020-05-29 05:55
If we have created a new project from vuepress cli, on a global install, how to fix it with `watchpack`?

**Comment by zhouhuan327** [comment] 2020-05-29 06:32
> "watchpack": "1.6.1"
> 
> ```shell
> npm i -D watchpack@1.6.1
> ```
> 
> I noticed that the webpack hot update plugin `watchpack` is now `1.7.2`
> I compared the previous project and found it was `1.6.1`
> So I tried to install this version
> It's ready for hot update
> 
> ```shell
> npx vuepress info
> 
> Environment Info:
> 
>   System:
>     OS: Windows 10 10.0.18363
>     CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
>   Binaries:
>     Node: 10.15.2 - D:\nodejs\version\node.EXE
>     Yarn: 1.22.4 - D:\YarnCache\bin\yarn.CMD
>     npm: 6.14.5 - D:\YarnCache\bin\npm.CMD
>   Browsers:
>     Edge: 44.18362.449.0
>   npmPackages:
>     @vuepress/core:  1.5.0
>     @vuepress/theme-default:  1.5.0
>     vuepress: ^1.5.0 => 1.5.0
>   npmGlobalPackages:
>     vuepress: Not Found
> ```
> 
> ~`yarn` installs `"watchpack": "^1.6.1"` separately in `webpack`~
> ~This automatically correlates to `1.7.2`~
> ~So it only works in `npm` mode~
> `yarn` solution is answered below
> 
> In a project created by `@vue/cli 4.3.1`, the `watchpack` is `1.7.2`, but it can still trigger hot updates
> Confused!

 ohhh it works

**Comment by 307590317** [comment] 2020-06-01 07:42
You can update the configuration in package.json as follows
```js
"devDependencies": {
    "vuepress": "^1.5.0",
    "watchpack": "1.6.1"
 }
```
then 
``` js
npm install
```
finally
``` js
npm start
```
hot reloading is ok

**Comment by sodes-gh** [comment] 2020-06-03 21:56
> You can update the configuration in package.json as follows
> 
> ```js
> "devDependencies": {
>     "vuepress": "^1.5.0",
>     "watchpack": "1.6.1"
>  }
> ```
> 
> then
> 
> ```js
> npm install
> ```
> 
> finally
> 
> ```js
> npm start
> ```
> 
> hot reloading is ok

yeah this solved my issue

**Comment by coffeephile** [comment] 2020-06-04 01:33
I've run into the same issue.
Everything worked fine on VuePress v1.4.1, but when upgrading to v1.5.0 hot reload stopped working.

Downgrading `watchpack` to `1.6.1` helped.
```
npm i watchpack@1.6.1 --save-dev
```

Thank you all a lot for investigating this issue. 🙇‍♂️

**Comment by BruceYuj** [comment] 2020-06-06 10:44
i've run into the same issue in VuePress v1.5.0(watchpack is v1.7.2)
so I downgrade `watchpack` to `1.6.1`, and it helps.

thanks a lot for investigating this issue.

**Comment by wen11497110** [comment] 2020-06-07 15:27
after i add watchpack 1.6.1, md file could hot reload, but .vuepress/config.js could not hot reload. 
hung at this step:
![image](https://user-images.githubusercontent.com/10792245/83973063-71181600-a916-11ea-9aa1-1eff586658ee.png)

**Comment by jd-0001** [comment] 2020-06-08 06:13
+1

**Comment by PentaTea** [comment] 2020-06-09 15:24
**牛批**

**Comment by bencodezen** [comment] 2020-06-09 15:58
Alright! Hopefully this is now fixed thanks to @pikax and @sodatea for their assistance. 

For those on v1.5.0, please make sure to upgrade to v1.5.1 and then you should be good.

I'll close the issue for now, but please let us know if it's still broken for you!

**Closed by bencodezen** 2020-06-09 15:58 UTC
Labels: priority: high, type: bug

**Comment by NicolasThierion** [comment] 2020-06-09 17:02
Thank you. I confirm the issue is solved for me!

**Comment by BaroDevelopment** [comment] 2020-06-09 17:12
Removed watchpack from my dependencies (just added it cause of this issue) and upgraded to 1.5.1

Works like a charm - thanks!

**Comment by thominal** [comment] 2020-06-09 17:18
Hi,
It works now well for .md files, but config.js do not hot reload anymore.

For info, I removed watchpack from dependencies and upgraded to 1.5.1

**Comment by pikax** [comment] 2020-06-09 17:35
@thominal this works for me 

```bash
yarn add vuepress --dev
mkdir docs
echo hello > docs/index.md
echo 'module.exports = { title: "test"}' > docs/.vuepress/config.js
yarn vuepress dev docs
```

**Comment by bencodezen** [comment] 2020-06-09 20:52
@thominal Thanks for reporting this. Could you go ahead and open a new issue with what you tried to do so I can replicate it?

**Comment by tecnoloco** [comment] 2020-06-09 22:10
version 1.5.1

- Updating .md files. Hot reload OK.

- Updating config.js. Hot reload Not Working. 

- Updating YAML Frontmatter in .md files. Hot reload Not working.

**Comment by pikax** [comment] 2020-06-10 11:21
@tecnoloco can you provide a repo where I can reproduce that, please?

**Comment by thominal** [comment] 2020-06-11 09:52
Hi,

@bencodezen @pilax

I try to recreate a new project from scratch: I have the same observations as @tecnoloco :

- No issue with .md files, hot reload works well
- However, I need to restart manually my server to see config.js changes. 

My config.js file is as simple as:

`module.exports = {
  title: 'Hello Wolrd',
  description: 'Just playing around'
}`

Thanks

**Comment by surjithctly** [comment] 2020-06-23 15:59
I tried everything in the above. But its not working for me too in windows. 

The terminal log updates and says build is finished. But its not updating in server. Even refresh not working. had to terminate the job and run `vuepress dev` again to see the changes. 

Please provide me a fix.

**Comment by bencodezen** [comment] 2020-06-23 16:15
Hi @surjithctly! We're tracking the bug regarding the config and frontmatter here: https://github.com/vuejs/vuepress/issues/2437

Are you still having issues with the markdown files not reloading?

**Comment by surjithctly** [comment] 2020-06-24 06:45
@bencodezen Yes. Markdown works fine. The data inside `---` 3 lines do not work.

**Comment by bencodezen** [comment] 2020-06-24 15:26
@surjithctly Got it. I would definitely add your comments and threads to #2437 then. Thank you!

**Comment by SimZhou** [comment] 2020-06-30 11:59
webpack downgraded to 1.6.1, but still not working. 

- [x] Changing content in .md file works
- [ ] Changing front matter in .md file NOT works
- [ ] Changing `config.js` NOT works

**Comment by aceven24** [comment] 2020-06-30 16:18
Same here, frontmatter in .md does not work.
I'm using a local custom theme
Also Typescript

Here is my info

Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
  Binaries:
    Node: 12.13.1 - ~\AppData\Local\Temp\yarn--1593533765469-0.49432315341001365\node.CMD
    Yarn: 1.21.1 - ~\AppData\Local\Temp\yarn--1593533765469-0.49432315341001365\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core:  1.5.2
    @vuepress/theme-default:  1.5.2
    vuepress: ^1.5.2 => 1.5.2
  npmGlobalPackages:
    vuepress: Not Found

**Comment by SimZhou** [comment] 2020-06-30 16:26
Try `npm vuepress dev docs --temp .temp`/`yarn vuepress dev docs --temp .temp` instead. See if it works for you. 

If yes you could write this into package.json: `"dev": "vuepress dev docs --temp .temp"`

**Comment by aceven24** [comment] 2020-06-30 16:27
> Try `npm vuepress dev docs --temp .temp`/`yarn vuepress dev docs --temp .temp` instead. See if it works for you.
> 
> If yes you could write this into package.json: `"dev": "vuepress dev docs --temp .temp"`

Tried that, even blew away my node_modules an yarn lock and reinstalled, same issue.. :-(

**Comment by andrea-ccc** [comment] 2020-07-17 08:02
Hi guys, just trying `vuepress` (v.1.3.1) on Node.js v12.18.2 and having the same problem.
Rolling back to Node.js  **v12.13.1** solved the issue.
Hope that helps.

Note: I always manage Node.js via [nvm](https://github.com/nvm-sh/nvm), so changing versions just for a project or even a session is pretty easy.

**Comment by sdwru** [comment] 2020-07-17 14:07
Any updates.  I'm having the same problem.  Using `yarn vuepress dev docs --temp .temp` doesn't work either.

**Comment by surjithctly** [comment] 2020-07-17 14:46
@sdwru Check  this open issue from 2019. Still not fixed #1283

**Comment by SimZhou** [comment] 2020-07-17 17:06
Evan is now making a new tool to solve it...
check [vuejs/vitepress#motivation](https://github.com/vuejs/vitepress#motivation)

**Comment by aceven24** [comment] 2020-07-18 02:09
Does not work for me I’m on 12.13.1

Sent from my iPhone

On Jul 17, 2020, at 4:02 AM, andrea-ccc <notifications@github.com> wrote:

﻿

Hi guys, just trying vuepress (v.1.3.1) on Node.js v12.18.2 and having the same problem.
Rolling back to Node.js v12.13.1 solved the issue.
Hope that helps.

Note: I always manage Node.js via nvm<https://github.com/nvm-sh/nvm>, so changing versions just for a project or even a session is pretty easy.

**Comment by surjithctly** [comment] 2020-07-18 02:52
> Evan is now making a new tool to solve it...
> check [vuejs/vitepress#motivation](https://github.com/vuejs/vitepress#motivation)

That’s an awesome news. Thanks for letting me know.

**Comment by sundayz** [comment] 2021-01-04 03:22
> 
> 
> Try `npm vuepress dev docs --temp .temp`/`yarn vuepress dev docs --temp .temp` instead. See if it works for you.
> 
> If yes you could write this into package.json: `"dev": "vuepress dev docs --temp .temp"`

This worked for me using 1.7.1 and npm, Windows 10. I don't know why or what it does.

**Comment by boris-savic** [comment] 2021-01-05 10:36
> > Try `npm vuepress dev docs --temp .temp`/`yarn vuepress dev docs --temp .temp` instead. See if it works for you.
> > If yes you could write this into package.json: `"dev": "vuepress dev docs --temp .temp"`
> 
> This worked for me using 1.7.1 and npm, Windows 10. I don't know why or what it does.

This works for me as well for config.js changes but not for index.md changes. 

Also running on Windows 10 with Node 14.15.0.

**Comment by meteorlxy** [comment] 2021-01-07 07:09
If you are not strictly using vue 2, try [vuepress 2](https://github.com/vuepress/vuepress-next) or [vitepress](https://github.com/vuejs/vitepress).

**Comment by SimZhou** [comment] 2021-01-10 04:02
> If you are not strictly using vue 2, try [vuepress 2](https://github.com/vuepress/vuepress-next) or [vitepress](https://github.com/vuejs/vitepress).

what's the difference between these two btw? Which one is official, or both are?

**Comment by meteorlxy** [comment] 2021-01-10 04:20
Both are vue.js team projects

**Comment by aku752** [comment] 2021-04-13 20:50
> Prueba `npm vuepress dev docs --temp .temp`/ en su `yarn vuepress dev docs --temp .temp`lugar. Mira si te funciona.
> 
> Si es así, puede escribir esto en package.json: `"dev": "vuepress dev docs --temp .temp"`

Gracias, muchas gracias :)

**Comment by aku752** [comment] 2021-04-13 20:58
> Prueba `npm vuepress dev docs --temp .temp`/ en su `yarn vuepress dev docs --temp .temp`lugar. Mira si te funciona.
> 
> Si es así, puede escribir esto en package.json: `"dev": "vuepress dev docs --temp .temp"`



> Try `npm vuepress dev docs --temp .temp`/`yarn vuepress dev docs --temp .temp` instead. See if it works for you.
> 
> If yes you could write this into package.json: `"dev": "vuepress dev docs --temp .temp"`

Gracias me funciono lo del .md y config. :)

**Comment by euberdeveloper** [comment] 2022-02-07 13:16
> Thanks to @SCWR I got it working by downgrading watchpack to 1.6.1 Added `resolutions` section to `package.json` and ran `yarn install`
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Hope this helps to anyone struggling with the same problem

For whom does not use yarn but npm, "ovverides" should be the analogue

**Comment by bbsimonbb** [comment] 2022-08-23 15:14
I added the resolutions section to package.json. Still broken. Ouch.
