### ISSUE TITLE
Document about permalinks doesn't explain the template variables clearly

### ISSUE THREAD

**Issue by fangbinwei** [vuejs/vuepress#1922] opened 2019-10-07 13:24 UTC
#### What problem does this feature solve?
[The document about permalinks](https://vuepress.vuejs.org/guide/permalinks.html#template-variables) doesn't explain the variable like `year,month,day` clearly. if we don't provide `date`, permalink will be like `/1970/01/01/doc`

#### What does the proposed API look like?
It will be better if these variables can be further explained

#### How should this be implemented in your opinion?
For example if you have the following file structure:
```bash
docs
├── 2019-10-06-example
│   └── permalink.md
└── example
    └── 2019-10-07-permalink.md
```
Then you will get following available pages with permalink pattern `'/:year/:month/:day/:slug'
`:
```bash
/2019/10/06/permalink/
/2019/10/07/permalink/
```
besides, you can provide frontmatter variables `date` in your markdown file
```yaml
---
date: 2019-10-07
---
```

#### Are you willing to work on this yourself?
my pleasure

**Comment by newsbielt703** [comment] 2020-01-31 05:41
I suppose it's duplicate of #1923.

**Closed by newsbielt703** 2020-01-31 05:41 UTC
