### ISSUE TITLE
Deprecated package

### ISSUE THREAD

**Issue by caxvis** [vuejs/vuepress#822] opened 2018-09-11 15:36 UTC
#### Version

`0.14.2`

#### Steps to reproduce

1. Make some changes
2. Push changes into GitHub (and it'll trigger a Travis build)
3. Build would failed in travis

#### What is expected?

Success build.

![screen shot 2018-09-11 at 22 35 05](https://user-images.githubusercontent.com/34530026/45370720-0045ac00-b613-11e8-8926-7d5f30ef7edf.png)

```
$ npm install -g vuepress
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
/home/travis/.nvm/versions/node/v8.11.4/bin/vuepress -> /home/travis/.nvm/versions/node/v8.11.4/lib/node_modules/vuepress/bin/vuepress.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/vuepress/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
+ vuepress@0.14.2
added 1246 packages in 46.276s
22.88s

$ vuepress build
 WAIT  Extracting site metadata...
[15:08:54] Compiling Client
[15:08:55] Compiling Server
(node:3512) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[15:09:06] Compiled Server in 12s
[15:09:12] Compiled Client in 17s
 WAIT  Rendering static HTML...
ll DONE  Success! Generated static files in .vuepress/dist.
```

#### What is actually happening?

Failed build.

![screen shot 2018-09-11 at 22 34 54](https://user-images.githubusercontent.com/34530026/45370742-0cca0480-b613-11e8-9756-ff213b1b88c9.png)

```
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for workbox-strategies@^3.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'workbox-google-analytics'
npm ERR! notarget
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-09-11T15_10_41_568Z-debug.log
The command "npm install -g vuepress" failed and exited with 1 during .
Your build has been stopped.
```
#### Other relevant information

- Your OS: `macOS 10.12.6`
- Node.js version: `v9.9.0`
- Browser version: `Google Chrome | 71.0.3548.0 (Official Build) canary (64-bit)`
- Is this a global or local install? `Global (install using Travis CI)`
- Which package manager did you use for the install? `NPM`

**Comment by ulivz** [comment] 2018-09-15 17:16
Duplicate of #632, See: https://github.com/vuejs/vuepress/issues/632#issuecomment-402916217

**Closed by ulivz** 2018-09-15 17:16 UTC
Labels: duplicate

**Comment by lkjimy** [comment] 2019-02-16 22:24
I tried to install locally and globally with npm and yarn and getting the same problem. Running on Windows 10 | (nvm) node v10.15.1 | npm v6.4.1

``
deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
``
