### ISSUE TITLE
Vuepress won't compile my markdown file?

### ISSUE THREAD

**Issue by zexingguo** [vuejs/vuepress#481] opened 2018-05-22 21:23 UTC
- WIN 10
- 8.9.4
- 0.9
- Chrome 66
- Global installed
- npm

I create a simple markdown file based on vuepress doc. However, when I run vuepress dev everything works without any error but the site shows weird diamond question mark with the word?

My guessing is that markdown file didn't get compiled, don't know if others ran into similar issue?

![vuepress](https://user-images.githubusercontent.com/11972292/40390951-ae3e9fd8-5dcb-11e8-8d11-4dcd4a7cd720.png)

**Comment by ulivz** [comment] 2018-05-23 03:05
Could you provide the reproduction repo?

**Comment by oxygen16** [comment] 2018-05-23 09:37
It looks like I have the same problem with you. use the getting-started guide but compile wrong
- WIN 10
- 8.11.1
- 0.9
- Chrome 66
- Global installed
- npm

**Comment by ulivz** [comment] 2018-05-23 12:14
@oxygen16 Please provide the reproduction repo.

**Comment by oxygen16** [comment] 2018-05-23 13:32
@ulivz https://github.com/oxygen16/reproduction

**Comment by ulivz** [comment] 2018-05-23 14:34
Duplicate of #276

See: https://github.com/vuejs/vuepress/issues/276#issuecomment-384930661

**Closed by ulivz** 2018-05-23 14:34 UTC
Labels: need repro

**Comment by oxygen16** [comment] 2018-05-24 10:20
In fact when Clone VuePress repo run as well garbled...

**Comment by ulivz** [comment] 2018-05-24 10:47
@oxygen16 Please check your encoding of your editor.
