### ISSUE TITLE
TypeError: renderChildren(...) is not iterable

### ISSUE THREAD

**Issue by ChinuxParibus** [vuejs/vuepress#414] opened 2018-05-11 11:58 UTC
OS Version: Debian GNU/Linux Jessie 8.10
Node.js Version: `8.9.3`
VuePress version: `0.3.1`
Install: Global
Package manager: `yarn`

I have my markdown content organized by date on a folder called `posts`:
```
posts
├── 2018
│   └── 05
│       ├── 03
│       │   └── alfabeto-de-javascript.md
│       └── 04
│           └── historia-del-blog.md
├── feed.json
└── README.md
```

When I execute the command `vuepress build` I get this error:
```
TypeError: renderChildren(...) is not iterable
    at children.map.c (server-bundle.js:2189:10)
    at Array.map (<anonymous>)
    at renderChildren (server-bundle.js:2185:61)
    at render (server-bundle.js:2162:21)
    at renderWithStyleInjection (server-bundle.js:195:16)
    at createFunctionalComponent (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:2128:521
    at VueComponent.renderList [as _l] (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.Sidebarvue_type_template_id_5b2591be_render (server-bundle.js:2128:258)
    at VueComponent.Vue._render (/home/chinux/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:7491:5)
    at RenderContext.renderNode (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:7407:5)
    at RenderContext.next (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:2428:14)
    at RenderContext.next (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:2441:12)
    at RenderContext.cachedWrite [as write] (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:2287:9)
    at RenderContext.next (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:2432:16)
    at RenderContext.cachedWrite [as write] (/home/chinux/.config/yarn/global/node_modules/vue-server-renderer/build.js:2287:9)
```

It only renders in HTML the first markdown document. Here is my `.vuepress/config.js`

```
 module.exports = {                                                               
   head: [                                                                        
     [ 'link', { rel: 'icon', href: `/assets/img/faviconjotaese.png` } ]          
   ],                                                                             
   ga: 'UA-90456269-1',                                                           
   title: 'JOTA ESE Y MÁS',                                                       
   description: 'Mi laboratorio de Javascript, sus herramientas derivadas y otras yerbas...',
   serviceWorker: true,                                                           
   editLinks: false,                                                              
   evergreen: true,                                                               
   themeConfig: {                                                                 
     nav: [                                                                       
       { text: 'ACERCA DE MÍ', link: '/about/'  },                                
       { text: 'UNA AYUDAÍTA', link: '/ayuda/'  },                                
       { text: 'DECÁLOGO HACKER', link: '/decalogo/' },                           
       { text: 'MANIFIESTO', link: '/manifiesto/' },                              
       { text: 'POSTS', link: '/posts/' }                                         
     ]                                                                            
   }                                                                              
 }   
```

**Comment by ulivz** [comment] 2018-05-11 12:25
Please update your vuepress to 0.8.4.

**Comment by ulivz** [comment] 2018-05-11 12:26
Duplicate of #34

**Closed by ulivz** 2018-05-11 12:25 UTC
